include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
    always_put_required_named_parameters_first: ignore
    document_ignores: ignore
    comment_references: ignore
    avoid_catches_without_on_clauses: ignore
