name: fhirr5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dependency_overrides:
  fhir_r5:
    path: packages/fhir_r5
  fhir_r5_at_rest:
    path: packages/fhir_r5_at_rest
  fhir_r5_path:
    path: packages/fhir_r5_path

dev_dependencies:
  melos: ^6.3.2
  very_good_analysis: ^7.0.0
