name: fhir_r6_auth
description: Secure authentication and authorization package for FHIR R6 applications implementing SMART on FHIR
version: 0.12.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_r6
issue_tracker: https://github.com/fhir-fli/fhir_r6/issues
documentation: https://pub.dev/documentation/fhir_r6_auth/latest/

topics:
  - fhir
  - smart-on-fhir
  - healthcare
  - authentication
  - oauth2

environment:
  sdk: ^3.5.0
  flutter: ">=3.10.0"

dependencies:
  fhir_auth: ^0.13.0
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.1.0
