import 'package:fhir_r5_mapping/fhir_r5_mapping.dart';

/// This function accepts a dynamic value, and a String type and attmpts
/// to create that FhirType
FhirBaseBuilder? emptyFromType(String type) {
  var fhirType = type.toLowerCase();
  if (fhirType.endsWith('builder')) {
    fhirType = fhirType.substring(0, fhirType.length - 7);
  }
  switch (fhirType) {
    case 'fhirbase64binary':
      return FhirBase64BinaryBuilder.empty();
    case 'base64binary':
      return FhirBase64BinaryBuilder.empty();
    case 'fhirboolean':
      return FhirBooleanBuilder.empty();
    case 'boolean':
      return FhirBooleanBuilder.empty();
    case 'fhircanonical':
      return FhirCanonicalBuilder.empty();
    case 'canonical':
      return FhirCanonicalBuilder.empty();
    case 'fhircode':
      return FhirCodeBuilder.empty();
    case 'code':
      return FhirCodeBuilder.empty();
    case 'fhirdate':
      return FhirDateBuilder.empty();
    case 'date':
      return FhirDateBuilder.empty();
    case 'fhirdatetime':
      return FhirDateTimeBuilder.empty();
    case 'datetime':
      return FhirDateTimeBuilder.empty();
    case 'fhirdecimal':
      return FhirDecimalBuilder.empty();
    case 'decimal':
      return FhirDecimalBuilder.empty();
    case 'fhirid':
      return FhirIdBuilder.empty();
    case 'id':
      return FhirIdBuilder.empty();
    case 'fhirinstant':
      return FhirInstantBuilder.empty();
    case 'instant':
      return FhirInstantBuilder.empty();
    case 'fhirinteger':
      return FhirIntegerBuilder.empty();
    case 'integer':
      return FhirIntegerBuilder.empty();
    case 'fhirmarkdown':
      return FhirMarkdownBuilder.empty();
    case 'markdown':
      return FhirMarkdownBuilder.empty();
    case 'fhiroid':
      return FhirOidBuilder.empty();
    case 'oid':
      return FhirOidBuilder.empty();
    case 'fhirpositiveint':
      return FhirPositiveIntBuilder.empty();
    case 'positiveint':
      return FhirPositiveIntBuilder.empty();
    case 'fhirstring':
      return FhirStringBuilder.empty();
    case 'string':
      return FhirStringBuilder.empty();
    case 'fhirtime':
      return FhirTimeBuilder.empty();
    case 'time':
      return FhirTimeBuilder.empty();
    case 'fhirunsignedint':
      return FhirUnsignedIntBuilder.empty();
    case 'unsignedint':
      return FhirUnsignedIntBuilder.empty();
    case 'fhiruri':
      return FhirUriBuilder.empty();
    case 'uri':
      return FhirUriBuilder.empty();
    case 'fhirurl':
      return FhirUrlBuilder.empty();
    case 'url':
      return FhirUrlBuilder.empty();
    case 'fhiruuid':
      return FhirUuidBuilder.empty();
    case 'uuid':
      return FhirUuidBuilder.empty();
    case 'fhirxhtml':
      return FhirXhtmlBuilder.empty();
    case 'xhtml':
      return FhirXhtmlBuilder.empty();
    case 'element':
      return ElementBuilder.empty();
    case 'fhirextension':
      return FhirExtensionBuilder.empty();
    case 'extension':
      return FhirExtensionBuilder.empty();
    case 'narrative':
      return NarrativeBuilder.empty();
    case 'annotation':
      return AnnotationBuilder.empty();
    case 'attachment':
      return AttachmentBuilder.empty();
    case 'identifier':
      return IdentifierBuilder.empty();
    case 'codeableconcept':
      return CodeableConceptBuilder.empty();
    case 'codeablereference':
      return CodeableReferenceBuilder.empty();
    case 'coding':
      return CodingBuilder.empty();
    case 'quantity':
      return QuantityBuilder.empty();
    case 'fhirduration':
      return FhirDurationBuilder.empty();
    case 'duration':
      return FhirDurationBuilder.empty();
    case 'distance':
      return DistanceBuilder.empty();
    case 'count':
      return CountBuilder.empty();
    case 'money':
      return MoneyBuilder.empty();
    case 'age':
      return AgeBuilder.empty();
    case 'range':
      return RangeBuilder.empty();
    case 'period':
      return PeriodBuilder.empty();
    case 'ratio':
      return RatioBuilder.empty();
    case 'ratiorange':
      return RatioRangeBuilder.empty();
    case 'reference':
      return ReferenceBuilder.empty();
    case 'sampleddata':
      return SampledDataBuilder.empty();
    case 'signature':
      return SignatureBuilder.empty();
    case 'humanname':
      return HumanNameBuilder.empty();
    case 'address':
      return AddressBuilder.empty();
    case 'contactpoint':
      return ContactPointBuilder.empty();
    case 'timing':
      return TimingBuilder.empty();
    case 'timingrepeat':
      return TimingRepeatBuilder.empty();
    case 'timing_repeat':
      return TimingRepeatBuilder.empty();
    case 'fhirmeta':
      return FhirMetaBuilder.empty();
    case 'meta':
      return FhirMetaBuilder.empty();
    case 'contactdetail':
      return ContactDetailBuilder.empty();
    case 'contributor':
      return ContributorBuilder.empty();
    case 'datarequirement':
      return DataRequirementBuilder.empty();
    case 'datarequirementcodefilter':
      return DataRequirementCodeFilterBuilder.empty();
    case 'datarequirement_codefilter':
      return DataRequirementCodeFilterBuilder.empty();
    case 'datarequirementdatefilter':
      return DataRequirementDateFilterBuilder.empty();
    case 'datarequirement_datefilter':
      return DataRequirementDateFilterBuilder.empty();
    case 'datarequirementsort':
      return DataRequirementSortBuilder.empty();
    case 'datarequirement_sort':
      return DataRequirementSortBuilder.empty();
    case 'parameterdefinition':
      return ParameterDefinitionBuilder.empty();
    case 'relatedartifact':
      return RelatedArtifactBuilder.empty();
    case 'triggerdefinition':
      return TriggerDefinitionBuilder.empty();
    case 'usagecontext':
      return UsageContextBuilder.empty();
    case 'dosage':
      return DosageBuilder.empty();
    case 'dosagedoseandrate':
      return DosageDoseAndRateBuilder.empty();
    case 'dosage_doseandrate':
      return DosageDoseAndRateBuilder.empty();
    case 'productshelflife':
      return ProductShelfLifeBuilder.empty();
    case 'marketingstatus':
      return MarketingStatusBuilder.empty();
    case 'fhirexpression':
      return FhirExpressionBuilder.empty();
    case 'expression':
      return FhirExpressionBuilder.empty();
    case 'elementdefinition':
      return ElementDefinitionBuilder.empty();
    case 'elementdefinitionslicing':
      return ElementDefinitionSlicingBuilder.empty();
    case 'elementdefinition_slicing':
      return ElementDefinitionSlicingBuilder.empty();
    case 'elementdefinitiondiscriminator':
      return ElementDefinitionDiscriminatorBuilder.empty();
    case 'elementdefinition_discriminator':
      return ElementDefinitionDiscriminatorBuilder.empty();
    case 'elementdefinitionbase':
      return ElementDefinitionBaseBuilder.empty();
    case 'elementdefinition_base':
      return ElementDefinitionBaseBuilder.empty();
    case 'elementdefinitiontype':
      return ElementDefinitionTypeBuilder.empty();
    case 'elementdefinition_type':
      return ElementDefinitionTypeBuilder.empty();
    case 'elementdefinitionexample':
      return ElementDefinitionExampleBuilder.empty();
    case 'elementdefinition_example':
      return ElementDefinitionExampleBuilder.empty();
    case 'elementdefinitionconstraint':
      return ElementDefinitionConstraintBuilder.empty();
    case 'elementdefinition_constraint':
      return ElementDefinitionConstraintBuilder.empty();
    case 'elementdefinitionbinding':
      return ElementDefinitionBindingBuilder.empty();
    case 'elementdefinition_binding':
      return ElementDefinitionBindingBuilder.empty();
    case 'elementdefinitionmapping':
      return ElementDefinitionMappingBuilder.empty();
    case 'elementdefinition_mapping':
      return ElementDefinitionMappingBuilder.empty();
    case 'account':
      return AccountBuilder.empty();
    case 'accountcoverage':
      return AccountCoverageBuilder.empty();
    case 'account_coverage':
      return AccountCoverageBuilder.empty();
    case 'accountguarantor':
      return AccountGuarantorBuilder.empty();
    case 'account_guarantor':
      return AccountGuarantorBuilder.empty();
    case 'activitydefinition':
      return ActivityDefinitionBuilder.empty();
    case 'activitydefinitionparticipant':
      return ActivityDefinitionParticipantBuilder.empty();
    case 'activitydefinition_participant':
      return ActivityDefinitionParticipantBuilder.empty();
    case 'activitydefinitiondynamicvalue':
      return ActivityDefinitionDynamicValueBuilder.empty();
    case 'activitydefinition_dynamicvalue':
      return ActivityDefinitionDynamicValueBuilder.empty();
    case 'administrableproductdefinition':
      return AdministrableProductDefinitionBuilder.empty();
    case 'administrableproductdefinitionproperty':
      return AdministrableProductDefinitionPropertyBuilder.empty();
    case 'administrableproductdefinition_property':
      return AdministrableProductDefinitionPropertyBuilder.empty();
    case 'administrableproductdefinitionrouteofadministration':
      return AdministrableProductDefinitionRouteOfAdministrationBuilder.empty();
    case 'administrableproductdefinition_routeofadministration':
      return AdministrableProductDefinitionRouteOfAdministrationBuilder.empty();
    case 'administrableproductdefinitiontargetspecies':
      return AdministrableProductDefinitionTargetSpeciesBuilder.empty();
    case 'administrableproductdefinition_targetspecies':
      return AdministrableProductDefinitionTargetSpeciesBuilder.empty();
    case 'administrableproductdefinitionwithdrawalperiod':
      return AdministrableProductDefinitionWithdrawalPeriodBuilder.empty();
    case 'administrableproductdefinition_withdrawalperiod':
      return AdministrableProductDefinitionWithdrawalPeriodBuilder.empty();
    case 'adverseevent':
      return AdverseEventBuilder.empty();
    case 'adverseeventsuspectentity':
      return AdverseEventSuspectEntityBuilder.empty();
    case 'adverseevent_suspectentity':
      return AdverseEventSuspectEntityBuilder.empty();
    case 'adverseeventcausality':
      return AdverseEventCausalityBuilder.empty();
    case 'adverseevent_causality':
      return AdverseEventCausalityBuilder.empty();
    case 'allergyintolerance':
      return AllergyIntoleranceBuilder.empty();
    case 'allergyintolerancereaction':
      return AllergyIntoleranceReactionBuilder.empty();
    case 'allergyintolerance_reaction':
      return AllergyIntoleranceReactionBuilder.empty();
    case 'appointment':
      return AppointmentBuilder.empty();
    case 'appointmentparticipant':
      return AppointmentParticipantBuilder.empty();
    case 'appointment_participant':
      return AppointmentParticipantBuilder.empty();
    case 'appointmentresponse':
      return AppointmentResponseBuilder.empty();
    case 'auditevent':
      return AuditEventBuilder.empty();
    case 'auditeventagent':
      return AuditEventAgentBuilder.empty();
    case 'auditevent_agent':
      return AuditEventAgentBuilder.empty();
    case 'auditeventsource':
      return AuditEventSourceBuilder.empty();
    case 'auditevent_source':
      return AuditEventSourceBuilder.empty();
    case 'auditevententity':
      return AuditEventEntityBuilder.empty();
    case 'auditevent_entity':
      return AuditEventEntityBuilder.empty();
    case 'auditeventdetail':
      return AuditEventDetailBuilder.empty();
    case 'auditevent_detail':
      return AuditEventDetailBuilder.empty();
    case 'basic':
      return BasicBuilder.empty();
    case 'binary':
      return BinaryBuilder.empty();
    case 'biologicallyderivedproduct':
      return BiologicallyDerivedProductBuilder.empty();
    case 'biologicallyderivedproductcollection':
      return BiologicallyDerivedProductCollectionBuilder.empty();
    case 'biologicallyderivedproduct_collection':
      return BiologicallyDerivedProductCollectionBuilder.empty();
    case 'bodystructure':
      return BodyStructureBuilder.empty();
    case 'bundle':
      return BundleBuilder.empty();
    case 'bundlelink':
      return BundleLinkBuilder.empty();
    case 'bundle_link':
      return BundleLinkBuilder.empty();
    case 'bundleentry':
      return BundleEntryBuilder.empty();
    case 'bundle_entry':
      return BundleEntryBuilder.empty();
    case 'bundlesearch':
      return BundleSearchBuilder.empty();
    case 'bundle_search':
      return BundleSearchBuilder.empty();
    case 'bundlerequest':
      return BundleRequestBuilder.empty();
    case 'bundle_request':
      return BundleRequestBuilder.empty();
    case 'bundleresponse':
      return BundleResponseBuilder.empty();
    case 'bundle_response':
      return BundleResponseBuilder.empty();
    case 'capabilitystatement':
      return CapabilityStatementBuilder.empty();
    case 'capabilitystatementsoftware':
      return CapabilityStatementSoftwareBuilder.empty();
    case 'capabilitystatement_software':
      return CapabilityStatementSoftwareBuilder.empty();
    case 'capabilitystatementimplementation':
      return CapabilityStatementImplementationBuilder.empty();
    case 'capabilitystatement_implementation':
      return CapabilityStatementImplementationBuilder.empty();
    case 'capabilitystatementrest':
      return CapabilityStatementRestBuilder.empty();
    case 'capabilitystatement_rest':
      return CapabilityStatementRestBuilder.empty();
    case 'capabilitystatementsecurity':
      return CapabilityStatementSecurityBuilder.empty();
    case 'capabilitystatement_security':
      return CapabilityStatementSecurityBuilder.empty();
    case 'capabilitystatementresource':
      return CapabilityStatementResourceBuilder.empty();
    case 'capabilitystatement_resource':
      return CapabilityStatementResourceBuilder.empty();
    case 'capabilitystatementinteraction':
      return CapabilityStatementInteractionBuilder.empty();
    case 'capabilitystatement_interaction':
      return CapabilityStatementInteractionBuilder.empty();
    case 'capabilitystatementsearchparam':
      return CapabilityStatementSearchParamBuilder.empty();
    case 'capabilitystatement_searchparam':
      return CapabilityStatementSearchParamBuilder.empty();
    case 'capabilitystatementoperation':
      return CapabilityStatementOperationBuilder.empty();
    case 'capabilitystatement_operation':
      return CapabilityStatementOperationBuilder.empty();
    case 'capabilitystatementinteraction1':
      return CapabilityStatementInteraction1Builder.empty();
    case 'capabilitystatement_interaction1':
      return CapabilityStatementInteraction1Builder.empty();
    case 'capabilitystatementmessaging':
      return CapabilityStatementMessagingBuilder.empty();
    case 'capabilitystatement_messaging':
      return CapabilityStatementMessagingBuilder.empty();
    case 'capabilitystatementendpoint':
      return CapabilityStatementEndpointBuilder.empty();
    case 'capabilitystatement_endpoint':
      return CapabilityStatementEndpointBuilder.empty();
    case 'capabilitystatementsupportedmessage':
      return CapabilityStatementSupportedMessageBuilder.empty();
    case 'capabilitystatement_supportedmessage':
      return CapabilityStatementSupportedMessageBuilder.empty();
    case 'capabilitystatementdocument':
      return CapabilityStatementDocumentBuilder.empty();
    case 'capabilitystatement_document':
      return CapabilityStatementDocumentBuilder.empty();
    case 'careplan':
      return CarePlanBuilder.empty();
    case 'careplanactivity':
      return CarePlanActivityBuilder.empty();
    case 'careplan_activity':
      return CarePlanActivityBuilder.empty();
    case 'careteam':
      return CareTeamBuilder.empty();
    case 'careteamparticipant':
      return CareTeamParticipantBuilder.empty();
    case 'careteam_participant':
      return CareTeamParticipantBuilder.empty();
    case 'chargeitem':
      return ChargeItemBuilder.empty();
    case 'chargeitemperformer':
      return ChargeItemPerformerBuilder.empty();
    case 'chargeitem_performer':
      return ChargeItemPerformerBuilder.empty();
    case 'chargeitemdefinition':
      return ChargeItemDefinitionBuilder.empty();
    case 'chargeitemdefinitionapplicability':
      return ChargeItemDefinitionApplicabilityBuilder.empty();
    case 'chargeitemdefinition_applicability':
      return ChargeItemDefinitionApplicabilityBuilder.empty();
    case 'chargeitemdefinitionpropertygroup':
      return ChargeItemDefinitionPropertyGroupBuilder.empty();
    case 'chargeitemdefinition_propertygroup':
      return ChargeItemDefinitionPropertyGroupBuilder.empty();
    case 'citation':
      return CitationBuilder.empty();
    case 'citationsummary':
      return CitationSummaryBuilder.empty();
    case 'citation_summary':
      return CitationSummaryBuilder.empty();
    case 'citationclassification':
      return CitationClassificationBuilder.empty();
    case 'citation_classification':
      return CitationClassificationBuilder.empty();
    case 'citationstatusdate':
      return CitationStatusDateBuilder.empty();
    case 'citation_statusdate':
      return CitationStatusDateBuilder.empty();
    case 'citationrelatesto':
      return CitationRelatesToBuilder.empty();
    case 'citation_relatesto':
      return CitationRelatesToBuilder.empty();
    case 'citationcitedartifact':
      return CitationCitedArtifactBuilder.empty();
    case 'citation_citedartifact':
      return CitationCitedArtifactBuilder.empty();
    case 'citationversion':
      return CitationVersionBuilder.empty();
    case 'citation_version':
      return CitationVersionBuilder.empty();
    case 'citationstatusdate1':
      return CitationStatusDate1Builder.empty();
    case 'citation_statusdate1':
      return CitationStatusDate1Builder.empty();
    case 'citationtitle':
      return CitationTitleBuilder.empty();
    case 'citation_title':
      return CitationTitleBuilder.empty();
    case 'citationabstract':
      return CitationAbstractBuilder.empty();
    case 'citation_abstract':
      return CitationAbstractBuilder.empty();
    case 'citationpart':
      return CitationPartBuilder.empty();
    case 'citation_part':
      return CitationPartBuilder.empty();
    case 'citationpublicationform':
      return CitationPublicationFormBuilder.empty();
    case 'citation_publicationform':
      return CitationPublicationFormBuilder.empty();
    case 'citationpublishedin':
      return CitationPublishedInBuilder.empty();
    case 'citation_publishedin':
      return CitationPublishedInBuilder.empty();
    case 'citationweblocation':
      return CitationWebLocationBuilder.empty();
    case 'citation_weblocation':
      return CitationWebLocationBuilder.empty();
    case 'citationclassification1':
      return CitationClassification1Builder.empty();
    case 'citation_classification1':
      return CitationClassification1Builder.empty();
    case 'citationcontributorship':
      return CitationContributorshipBuilder.empty();
    case 'citation_contributorship':
      return CitationContributorshipBuilder.empty();
    case 'citationentry':
      return CitationEntryBuilder.empty();
    case 'citation_entry':
      return CitationEntryBuilder.empty();
    case 'citationcontributioninstance':
      return CitationContributionInstanceBuilder.empty();
    case 'citation_contributioninstance':
      return CitationContributionInstanceBuilder.empty();
    case 'citationsummary1':
      return CitationSummary1Builder.empty();
    case 'citation_summary1':
      return CitationSummary1Builder.empty();
    case 'claim':
      return ClaimBuilder.empty();
    case 'claimrelated':
      return ClaimRelatedBuilder.empty();
    case 'claim_related':
      return ClaimRelatedBuilder.empty();
    case 'claimpayee':
      return ClaimPayeeBuilder.empty();
    case 'claim_payee':
      return ClaimPayeeBuilder.empty();
    case 'claimcareteam':
      return ClaimCareTeamBuilder.empty();
    case 'claim_careteam':
      return ClaimCareTeamBuilder.empty();
    case 'claimsupportinginfo':
      return ClaimSupportingInfoBuilder.empty();
    case 'claim_supportinginfo':
      return ClaimSupportingInfoBuilder.empty();
    case 'claimdiagnosis':
      return ClaimDiagnosisBuilder.empty();
    case 'claim_diagnosis':
      return ClaimDiagnosisBuilder.empty();
    case 'claimprocedure':
      return ClaimProcedureBuilder.empty();
    case 'claim_procedure':
      return ClaimProcedureBuilder.empty();
    case 'claiminsurance':
      return ClaimInsuranceBuilder.empty();
    case 'claim_insurance':
      return ClaimInsuranceBuilder.empty();
    case 'claimaccident':
      return ClaimAccidentBuilder.empty();
    case 'claim_accident':
      return ClaimAccidentBuilder.empty();
    case 'claimitem':
      return ClaimItemBuilder.empty();
    case 'claim_item':
      return ClaimItemBuilder.empty();
    case 'claimdetail':
      return ClaimDetailBuilder.empty();
    case 'claim_detail':
      return ClaimDetailBuilder.empty();
    case 'claimsubdetail':
      return ClaimSubDetailBuilder.empty();
    case 'claim_subdetail':
      return ClaimSubDetailBuilder.empty();
    case 'claimresponse':
      return ClaimResponseBuilder.empty();
    case 'claimresponseitem':
      return ClaimResponseItemBuilder.empty();
    case 'claimresponse_item':
      return ClaimResponseItemBuilder.empty();
    case 'claimresponseadjudication':
      return ClaimResponseAdjudicationBuilder.empty();
    case 'claimresponse_adjudication':
      return ClaimResponseAdjudicationBuilder.empty();
    case 'claimresponsedetail':
      return ClaimResponseDetailBuilder.empty();
    case 'claimresponse_detail':
      return ClaimResponseDetailBuilder.empty();
    case 'claimresponsesubdetail':
      return ClaimResponseSubDetailBuilder.empty();
    case 'claimresponse_subdetail':
      return ClaimResponseSubDetailBuilder.empty();
    case 'claimresponseadditem':
      return ClaimResponseAddItemBuilder.empty();
    case 'claimresponse_additem':
      return ClaimResponseAddItemBuilder.empty();
    case 'claimresponsedetail1':
      return ClaimResponseDetail1Builder.empty();
    case 'claimresponse_detail1':
      return ClaimResponseDetail1Builder.empty();
    case 'claimresponsesubdetail1':
      return ClaimResponseSubDetail1Builder.empty();
    case 'claimresponse_subdetail1':
      return ClaimResponseSubDetail1Builder.empty();
    case 'claimresponsetotal':
      return ClaimResponseTotalBuilder.empty();
    case 'claimresponse_total':
      return ClaimResponseTotalBuilder.empty();
    case 'claimresponsepayment':
      return ClaimResponsePaymentBuilder.empty();
    case 'claimresponse_payment':
      return ClaimResponsePaymentBuilder.empty();
    case 'claimresponseprocessnote':
      return ClaimResponseProcessNoteBuilder.empty();
    case 'claimresponse_processnote':
      return ClaimResponseProcessNoteBuilder.empty();
    case 'claimresponseinsurance':
      return ClaimResponseInsuranceBuilder.empty();
    case 'claimresponse_insurance':
      return ClaimResponseInsuranceBuilder.empty();
    case 'claimresponseerror':
      return ClaimResponseErrorBuilder.empty();
    case 'claimresponse_error':
      return ClaimResponseErrorBuilder.empty();
    case 'clinicalimpression':
      return ClinicalImpressionBuilder.empty();
    case 'clinicalimpressionfinding':
      return ClinicalImpressionFindingBuilder.empty();
    case 'clinicalimpression_finding':
      return ClinicalImpressionFindingBuilder.empty();
    case 'clinicalusedefinition':
      return ClinicalUseDefinitionBuilder.empty();
    case 'clinicalusedefinitioncontraindication':
      return ClinicalUseDefinitionContraindicationBuilder.empty();
    case 'clinicalusedefinition_contraindication':
      return ClinicalUseDefinitionContraindicationBuilder.empty();
    case 'clinicalusedefinitionothertherapy':
      return ClinicalUseDefinitionOtherTherapyBuilder.empty();
    case 'clinicalusedefinition_othertherapy':
      return ClinicalUseDefinitionOtherTherapyBuilder.empty();
    case 'clinicalusedefinitionindication':
      return ClinicalUseDefinitionIndicationBuilder.empty();
    case 'clinicalusedefinition_indication':
      return ClinicalUseDefinitionIndicationBuilder.empty();
    case 'clinicalusedefinitioninteraction':
      return ClinicalUseDefinitionInteractionBuilder.empty();
    case 'clinicalusedefinition_interaction':
      return ClinicalUseDefinitionInteractionBuilder.empty();
    case 'clinicalusedefinitioninteractant':
      return ClinicalUseDefinitionInteractantBuilder.empty();
    case 'clinicalusedefinition_interactant':
      return ClinicalUseDefinitionInteractantBuilder.empty();
    case 'clinicalusedefinitionundesirableeffect':
      return ClinicalUseDefinitionUndesirableEffectBuilder.empty();
    case 'clinicalusedefinition_undesirableeffect':
      return ClinicalUseDefinitionUndesirableEffectBuilder.empty();
    case 'clinicalusedefinitionwarning':
      return ClinicalUseDefinitionWarningBuilder.empty();
    case 'clinicalusedefinition_warning':
      return ClinicalUseDefinitionWarningBuilder.empty();
    case 'codesystem':
      return CodeSystemBuilder.empty();
    case 'codesystemfilter':
      return CodeSystemFilterBuilder.empty();
    case 'codesystem_filter':
      return CodeSystemFilterBuilder.empty();
    case 'codesystemproperty':
      return CodeSystemPropertyBuilder.empty();
    case 'codesystem_property':
      return CodeSystemPropertyBuilder.empty();
    case 'codesystemconcept':
      return CodeSystemConceptBuilder.empty();
    case 'codesystem_concept':
      return CodeSystemConceptBuilder.empty();
    case 'codesystemdesignation':
      return CodeSystemDesignationBuilder.empty();
    case 'codesystem_designation':
      return CodeSystemDesignationBuilder.empty();
    case 'codesystemproperty1':
      return CodeSystemProperty1Builder.empty();
    case 'codesystem_property1':
      return CodeSystemProperty1Builder.empty();
    case 'communication':
      return CommunicationBuilder.empty();
    case 'communicationpayload':
      return CommunicationPayloadBuilder.empty();
    case 'communication_payload':
      return CommunicationPayloadBuilder.empty();
    case 'communicationrequest':
      return CommunicationRequestBuilder.empty();
    case 'communicationrequestpayload':
      return CommunicationRequestPayloadBuilder.empty();
    case 'communicationrequest_payload':
      return CommunicationRequestPayloadBuilder.empty();
    case 'compartmentdefinition':
      return CompartmentDefinitionBuilder.empty();
    case 'compartmentdefinitionresource':
      return CompartmentDefinitionResourceBuilder.empty();
    case 'compartmentdefinition_resource':
      return CompartmentDefinitionResourceBuilder.empty();
    case 'composition':
      return CompositionBuilder.empty();
    case 'compositionattester':
      return CompositionAttesterBuilder.empty();
    case 'composition_attester':
      return CompositionAttesterBuilder.empty();
    case 'compositionevent':
      return CompositionEventBuilder.empty();
    case 'composition_event':
      return CompositionEventBuilder.empty();
    case 'compositionsection':
      return CompositionSectionBuilder.empty();
    case 'composition_section':
      return CompositionSectionBuilder.empty();
    case 'conceptmap':
      return ConceptMapBuilder.empty();
    case 'conceptmapgroup':
      return ConceptMapGroupBuilder.empty();
    case 'conceptmap_group':
      return ConceptMapGroupBuilder.empty();
    case 'conceptmapelement':
      return ConceptMapElementBuilder.empty();
    case 'conceptmap_element':
      return ConceptMapElementBuilder.empty();
    case 'conceptmaptarget':
      return ConceptMapTargetBuilder.empty();
    case 'conceptmap_target':
      return ConceptMapTargetBuilder.empty();
    case 'conceptmapdependson':
      return ConceptMapDependsOnBuilder.empty();
    case 'conceptmap_dependson':
      return ConceptMapDependsOnBuilder.empty();
    case 'conceptmapunmapped':
      return ConceptMapUnmappedBuilder.empty();
    case 'conceptmap_unmapped':
      return ConceptMapUnmappedBuilder.empty();
    case 'condition':
      return ConditionBuilder.empty();
    case 'conditionstage':
      return ConditionStageBuilder.empty();
    case 'condition_stage':
      return ConditionStageBuilder.empty();
    case 'consent':
      return ConsentBuilder.empty();
    case 'consentverification':
      return ConsentVerificationBuilder.empty();
    case 'consent_verification':
      return ConsentVerificationBuilder.empty();
    case 'consentprovision':
      return ConsentProvisionBuilder.empty();
    case 'consent_provision':
      return ConsentProvisionBuilder.empty();
    case 'consentactor':
      return ConsentActorBuilder.empty();
    case 'consent_actor':
      return ConsentActorBuilder.empty();
    case 'consentdata':
      return ConsentDataBuilder.empty();
    case 'consent_data':
      return ConsentDataBuilder.empty();
    case 'contract':
      return ContractBuilder.empty();
    case 'contractcontentdefinition':
      return ContractContentDefinitionBuilder.empty();
    case 'contract_contentdefinition':
      return ContractContentDefinitionBuilder.empty();
    case 'contractterm':
      return ContractTermBuilder.empty();
    case 'contract_term':
      return ContractTermBuilder.empty();
    case 'contractsecuritylabel':
      return ContractSecurityLabelBuilder.empty();
    case 'contract_securitylabel':
      return ContractSecurityLabelBuilder.empty();
    case 'contractoffer':
      return ContractOfferBuilder.empty();
    case 'contract_offer':
      return ContractOfferBuilder.empty();
    case 'contractparty':
      return ContractPartyBuilder.empty();
    case 'contract_party':
      return ContractPartyBuilder.empty();
    case 'contractanswer':
      return ContractAnswerBuilder.empty();
    case 'contract_answer':
      return ContractAnswerBuilder.empty();
    case 'contractasset':
      return ContractAssetBuilder.empty();
    case 'contract_asset':
      return ContractAssetBuilder.empty();
    case 'contractcontext':
      return ContractContextBuilder.empty();
    case 'contract_context':
      return ContractContextBuilder.empty();
    case 'contractvalueditem':
      return ContractValuedItemBuilder.empty();
    case 'contract_valueditem':
      return ContractValuedItemBuilder.empty();
    case 'contractaction':
      return ContractActionBuilder.empty();
    case 'contract_action':
      return ContractActionBuilder.empty();
    case 'contractsubject':
      return ContractSubjectBuilder.empty();
    case 'contract_subject':
      return ContractSubjectBuilder.empty();
    case 'contractsigner':
      return ContractSignerBuilder.empty();
    case 'contract_signer':
      return ContractSignerBuilder.empty();
    case 'contractfriendly':
      return ContractFriendlyBuilder.empty();
    case 'contract_friendly':
      return ContractFriendlyBuilder.empty();
    case 'contractlegal':
      return ContractLegalBuilder.empty();
    case 'contract_legal':
      return ContractLegalBuilder.empty();
    case 'contractrule':
      return ContractRuleBuilder.empty();
    case 'contract_rule':
      return ContractRuleBuilder.empty();
    case 'coverage':
      return CoverageBuilder.empty();
    case 'coverageclass':
      return CoverageClassBuilder.empty();
    case 'coverage_class':
      return CoverageClassBuilder.empty();
    case 'coveragecosttobeneficiary':
      return CoverageCostToBeneficiaryBuilder.empty();
    case 'coverage_costtobeneficiary':
      return CoverageCostToBeneficiaryBuilder.empty();
    case 'coverageexception':
      return CoverageExceptionBuilder.empty();
    case 'coverage_exception':
      return CoverageExceptionBuilder.empty();
    case 'coverageeligibilityrequest':
      return CoverageEligibilityRequestBuilder.empty();
    case 'coverageeligibilityrequestsupportinginfo':
      return CoverageEligibilityRequestSupportingInfoBuilder.empty();
    case 'coverageeligibilityrequest_supportinginfo':
      return CoverageEligibilityRequestSupportingInfoBuilder.empty();
    case 'coverageeligibilityrequestinsurance':
      return CoverageEligibilityRequestInsuranceBuilder.empty();
    case 'coverageeligibilityrequest_insurance':
      return CoverageEligibilityRequestInsuranceBuilder.empty();
    case 'coverageeligibilityrequestitem':
      return CoverageEligibilityRequestItemBuilder.empty();
    case 'coverageeligibilityrequest_item':
      return CoverageEligibilityRequestItemBuilder.empty();
    case 'coverageeligibilityrequestdiagnosis':
      return CoverageEligibilityRequestDiagnosisBuilder.empty();
    case 'coverageeligibilityrequest_diagnosis':
      return CoverageEligibilityRequestDiagnosisBuilder.empty();
    case 'coverageeligibilityresponse':
      return CoverageEligibilityResponseBuilder.empty();
    case 'coverageeligibilityresponseinsurance':
      return CoverageEligibilityResponseInsuranceBuilder.empty();
    case 'coverageeligibilityresponse_insurance':
      return CoverageEligibilityResponseInsuranceBuilder.empty();
    case 'coverageeligibilityresponseitem':
      return CoverageEligibilityResponseItemBuilder.empty();
    case 'coverageeligibilityresponse_item':
      return CoverageEligibilityResponseItemBuilder.empty();
    case 'coverageeligibilityresponsebenefit':
      return CoverageEligibilityResponseBenefitBuilder.empty();
    case 'coverageeligibilityresponse_benefit':
      return CoverageEligibilityResponseBenefitBuilder.empty();
    case 'coverageeligibilityresponseerror':
      return CoverageEligibilityResponseErrorBuilder.empty();
    case 'coverageeligibilityresponse_error':
      return CoverageEligibilityResponseErrorBuilder.empty();
    case 'detectedissue':
      return DetectedIssueBuilder.empty();
    case 'detectedissueevidence':
      return DetectedIssueEvidenceBuilder.empty();
    case 'detectedissue_evidence':
      return DetectedIssueEvidenceBuilder.empty();
    case 'detectedissuemitigation':
      return DetectedIssueMitigationBuilder.empty();
    case 'detectedissue_mitigation':
      return DetectedIssueMitigationBuilder.empty();
    case 'device':
      return DeviceBuilder.empty();
    case 'deviceudicarrier':
      return DeviceUdiCarrierBuilder.empty();
    case 'device_udicarrier':
      return DeviceUdiCarrierBuilder.empty();
    case 'deviceversion':
      return DeviceVersionBuilder.empty();
    case 'device_version':
      return DeviceVersionBuilder.empty();
    case 'deviceproperty':
      return DevicePropertyBuilder.empty();
    case 'device_property':
      return DevicePropertyBuilder.empty();
    case 'devicedefinition':
      return DeviceDefinitionBuilder.empty();
    case 'devicedefinitionudideviceidentifier':
      return DeviceDefinitionUdiDeviceIdentifierBuilder.empty();
    case 'devicedefinition_udideviceidentifier':
      return DeviceDefinitionUdiDeviceIdentifierBuilder.empty();
    case 'devicedefinitiondevicename':
      return DeviceDefinitionDeviceNameBuilder.empty();
    case 'devicedefinition_devicename':
      return DeviceDefinitionDeviceNameBuilder.empty();
    case 'devicedefinitionproperty':
      return DeviceDefinitionPropertyBuilder.empty();
    case 'devicedefinition_property':
      return DeviceDefinitionPropertyBuilder.empty();
    case 'devicedefinitionmaterial':
      return DeviceDefinitionMaterialBuilder.empty();
    case 'devicedefinition_material':
      return DeviceDefinitionMaterialBuilder.empty();
    case 'devicemetric':
      return DeviceMetricBuilder.empty();
    case 'devicemetriccalibration':
      return DeviceMetricCalibrationBuilder.empty();
    case 'devicemetric_calibration':
      return DeviceMetricCalibrationBuilder.empty();
    case 'devicerequest':
      return DeviceRequestBuilder.empty();
    case 'devicerequestparameter':
      return DeviceRequestParameterBuilder.empty();
    case 'devicerequest_parameter':
      return DeviceRequestParameterBuilder.empty();
    case 'diagnosticreport':
      return DiagnosticReportBuilder.empty();
    case 'diagnosticreportmedia':
      return DiagnosticReportMediaBuilder.empty();
    case 'diagnosticreport_media':
      return DiagnosticReportMediaBuilder.empty();
    case 'documentreference':
      return DocumentReferenceBuilder.empty();
    case 'documentreferencerelatesto':
      return DocumentReferenceRelatesToBuilder.empty();
    case 'documentreference_relatesto':
      return DocumentReferenceRelatesToBuilder.empty();
    case 'documentreferencecontent':
      return DocumentReferenceContentBuilder.empty();
    case 'documentreference_content':
      return DocumentReferenceContentBuilder.empty();
    case 'encounter':
      return EncounterBuilder.empty();
    case 'encounterparticipant':
      return EncounterParticipantBuilder.empty();
    case 'encounter_participant':
      return EncounterParticipantBuilder.empty();
    case 'encounterdiagnosis':
      return EncounterDiagnosisBuilder.empty();
    case 'encounter_diagnosis':
      return EncounterDiagnosisBuilder.empty();
    case 'encounterlocation':
      return EncounterLocationBuilder.empty();
    case 'encounter_location':
      return EncounterLocationBuilder.empty();
    case 'fhirendpoint':
      return FhirEndpointBuilder.empty();
    case 'endpoint':
      return FhirEndpointBuilder.empty();
    case 'enrollmentrequest':
      return EnrollmentRequestBuilder.empty();
    case 'enrollmentresponse':
      return EnrollmentResponseBuilder.empty();
    case 'episodeofcare':
      return EpisodeOfCareBuilder.empty();
    case 'episodeofcarestatushistory':
      return EpisodeOfCareStatusHistoryBuilder.empty();
    case 'episodeofcare_statushistory':
      return EpisodeOfCareStatusHistoryBuilder.empty();
    case 'episodeofcarediagnosis':
      return EpisodeOfCareDiagnosisBuilder.empty();
    case 'episodeofcare_diagnosis':
      return EpisodeOfCareDiagnosisBuilder.empty();
    case 'eventdefinition':
      return EventDefinitionBuilder.empty();
    case 'evidence':
      return EvidenceBuilder.empty();
    case 'evidencevariabledefinition':
      return EvidenceVariableDefinitionBuilder.empty();
    case 'evidence_variabledefinition':
      return EvidenceVariableDefinitionBuilder.empty();
    case 'evidencestatistic':
      return EvidenceStatisticBuilder.empty();
    case 'evidence_statistic':
      return EvidenceStatisticBuilder.empty();
    case 'evidencesamplesize':
      return EvidenceSampleSizeBuilder.empty();
    case 'evidence_samplesize':
      return EvidenceSampleSizeBuilder.empty();
    case 'evidenceattributeestimate':
      return EvidenceAttributeEstimateBuilder.empty();
    case 'evidence_attributeestimate':
      return EvidenceAttributeEstimateBuilder.empty();
    case 'evidencemodelcharacteristic':
      return EvidenceModelCharacteristicBuilder.empty();
    case 'evidence_modelcharacteristic':
      return EvidenceModelCharacteristicBuilder.empty();
    case 'evidencemodelcharacteristicvariable':
      return EvidenceModelCharacteristicVariableBuilder.empty();
    case 'evidence_variable':
      return EvidenceModelCharacteristicVariableBuilder.empty();
    case 'evidencevariable':
      return EvidenceModelCharacteristicVariableBuilder.empty();
    case 'evidencecertainty':
      return EvidenceCertaintyBuilder.empty();
    case 'evidence_certainty':
      return EvidenceCertaintyBuilder.empty();
    case 'evidencereport':
      return EvidenceReportBuilder.empty();
    case 'evidencereportsubject':
      return EvidenceReportSubjectBuilder.empty();
    case 'evidencereport_subject':
      return EvidenceReportSubjectBuilder.empty();
    case 'evidencereportcharacteristic':
      return EvidenceReportCharacteristicBuilder.empty();
    case 'evidencereport_characteristic':
      return EvidenceReportCharacteristicBuilder.empty();
    case 'evidencereportrelatesto':
      return EvidenceReportRelatesToBuilder.empty();
    case 'evidencereport_relatesto':
      return EvidenceReportRelatesToBuilder.empty();
    case 'evidencereportsection':
      return EvidenceReportSectionBuilder.empty();
    case 'evidencereport_section':
      return EvidenceReportSectionBuilder.empty();
    case 'evidencevariablecharacteristic':
      return EvidenceVariableCharacteristicBuilder.empty();
    case 'evidencevariable_characteristic':
      return EvidenceVariableCharacteristicBuilder.empty();
    case 'evidencevariablecategory':
      return EvidenceVariableCategoryBuilder.empty();
    case 'evidencevariable_category':
      return EvidenceVariableCategoryBuilder.empty();
    case 'examplescenario':
      return ExampleScenarioBuilder.empty();
    case 'examplescenarioactor':
      return ExampleScenarioActorBuilder.empty();
    case 'examplescenario_actor':
      return ExampleScenarioActorBuilder.empty();
    case 'examplescenarioinstance':
      return ExampleScenarioInstanceBuilder.empty();
    case 'examplescenario_instance':
      return ExampleScenarioInstanceBuilder.empty();
    case 'examplescenarioversion':
      return ExampleScenarioVersionBuilder.empty();
    case 'examplescenario_version':
      return ExampleScenarioVersionBuilder.empty();
    case 'examplescenariocontainedinstance':
      return ExampleScenarioContainedInstanceBuilder.empty();
    case 'examplescenario_containedinstance':
      return ExampleScenarioContainedInstanceBuilder.empty();
    case 'examplescenarioprocess':
      return ExampleScenarioProcessBuilder.empty();
    case 'examplescenario_process':
      return ExampleScenarioProcessBuilder.empty();
    case 'examplescenariostep':
      return ExampleScenarioStepBuilder.empty();
    case 'examplescenario_step':
      return ExampleScenarioStepBuilder.empty();
    case 'examplescenariooperation':
      return ExampleScenarioOperationBuilder.empty();
    case 'examplescenario_operation':
      return ExampleScenarioOperationBuilder.empty();
    case 'examplescenarioalternative':
      return ExampleScenarioAlternativeBuilder.empty();
    case 'examplescenario_alternative':
      return ExampleScenarioAlternativeBuilder.empty();
    case 'explanationofbenefit':
      return ExplanationOfBenefitBuilder.empty();
    case 'explanationofbenefitrelated':
      return ExplanationOfBenefitRelatedBuilder.empty();
    case 'explanationofbenefit_related':
      return ExplanationOfBenefitRelatedBuilder.empty();
    case 'explanationofbenefitpayee':
      return ExplanationOfBenefitPayeeBuilder.empty();
    case 'explanationofbenefit_payee':
      return ExplanationOfBenefitPayeeBuilder.empty();
    case 'explanationofbenefitcareteam':
      return ExplanationOfBenefitCareTeamBuilder.empty();
    case 'explanationofbenefit_careteam':
      return ExplanationOfBenefitCareTeamBuilder.empty();
    case 'explanationofbenefitsupportinginfo':
      return ExplanationOfBenefitSupportingInfoBuilder.empty();
    case 'explanationofbenefit_supportinginfo':
      return ExplanationOfBenefitSupportingInfoBuilder.empty();
    case 'explanationofbenefitdiagnosis':
      return ExplanationOfBenefitDiagnosisBuilder.empty();
    case 'explanationofbenefit_diagnosis':
      return ExplanationOfBenefitDiagnosisBuilder.empty();
    case 'explanationofbenefitprocedure':
      return ExplanationOfBenefitProcedureBuilder.empty();
    case 'explanationofbenefit_procedure':
      return ExplanationOfBenefitProcedureBuilder.empty();
    case 'explanationofbenefitinsurance':
      return ExplanationOfBenefitInsuranceBuilder.empty();
    case 'explanationofbenefit_insurance':
      return ExplanationOfBenefitInsuranceBuilder.empty();
    case 'explanationofbenefitaccident':
      return ExplanationOfBenefitAccidentBuilder.empty();
    case 'explanationofbenefit_accident':
      return ExplanationOfBenefitAccidentBuilder.empty();
    case 'explanationofbenefititem':
      return ExplanationOfBenefitItemBuilder.empty();
    case 'explanationofbenefit_item':
      return ExplanationOfBenefitItemBuilder.empty();
    case 'explanationofbenefitadjudication':
      return ExplanationOfBenefitAdjudicationBuilder.empty();
    case 'explanationofbenefit_adjudication':
      return ExplanationOfBenefitAdjudicationBuilder.empty();
    case 'explanationofbenefitdetail':
      return ExplanationOfBenefitDetailBuilder.empty();
    case 'explanationofbenefit_detail':
      return ExplanationOfBenefitDetailBuilder.empty();
    case 'explanationofbenefitsubdetail':
      return ExplanationOfBenefitSubDetailBuilder.empty();
    case 'explanationofbenefit_subdetail':
      return ExplanationOfBenefitSubDetailBuilder.empty();
    case 'explanationofbenefitadditem':
      return ExplanationOfBenefitAddItemBuilder.empty();
    case 'explanationofbenefit_additem':
      return ExplanationOfBenefitAddItemBuilder.empty();
    case 'explanationofbenefitdetail1':
      return ExplanationOfBenefitDetail1Builder.empty();
    case 'explanationofbenefit_detail1':
      return ExplanationOfBenefitDetail1Builder.empty();
    case 'explanationofbenefitsubdetail1':
      return ExplanationOfBenefitSubDetail1Builder.empty();
    case 'explanationofbenefit_subdetail1':
      return ExplanationOfBenefitSubDetail1Builder.empty();
    case 'explanationofbenefittotal':
      return ExplanationOfBenefitTotalBuilder.empty();
    case 'explanationofbenefit_total':
      return ExplanationOfBenefitTotalBuilder.empty();
    case 'explanationofbenefitpayment':
      return ExplanationOfBenefitPaymentBuilder.empty();
    case 'explanationofbenefit_payment':
      return ExplanationOfBenefitPaymentBuilder.empty();
    case 'explanationofbenefitprocessnote':
      return ExplanationOfBenefitProcessNoteBuilder.empty();
    case 'explanationofbenefit_processnote':
      return ExplanationOfBenefitProcessNoteBuilder.empty();
    case 'explanationofbenefitbenefitbalance':
      return ExplanationOfBenefitBenefitBalanceBuilder.empty();
    case 'explanationofbenefit_benefitbalance':
      return ExplanationOfBenefitBenefitBalanceBuilder.empty();
    case 'explanationofbenefitfinancial':
      return ExplanationOfBenefitFinancialBuilder.empty();
    case 'explanationofbenefit_financial':
      return ExplanationOfBenefitFinancialBuilder.empty();
    case 'familymemberhistory':
      return FamilyMemberHistoryBuilder.empty();
    case 'familymemberhistorycondition':
      return FamilyMemberHistoryConditionBuilder.empty();
    case 'familymemberhistory_condition':
      return FamilyMemberHistoryConditionBuilder.empty();
    case 'flag':
      return FlagBuilder.empty();
    case 'goal':
      return GoalBuilder.empty();
    case 'goaltarget':
      return GoalTargetBuilder.empty();
    case 'goal_target':
      return GoalTargetBuilder.empty();
    case 'graphdefinition':
      return GraphDefinitionBuilder.empty();
    case 'graphdefinitionlink':
      return GraphDefinitionLinkBuilder.empty();
    case 'graphdefinition_link':
      return GraphDefinitionLinkBuilder.empty();
    case 'graphdefinitioncompartment':
      return GraphDefinitionCompartmentBuilder.empty();
    case 'graphdefinition_compartment':
      return GraphDefinitionCompartmentBuilder.empty();
    case 'fhirgroup':
      return FhirGroupBuilder.empty();
    case 'group':
      return FhirGroupBuilder.empty();
    case 'groupcharacteristic':
      return GroupCharacteristicBuilder.empty();
    case 'group_characteristic':
      return GroupCharacteristicBuilder.empty();
    case 'groupmember':
      return GroupMemberBuilder.empty();
    case 'group_member':
      return GroupMemberBuilder.empty();
    case 'guidanceresponse':
      return GuidanceResponseBuilder.empty();
    case 'healthcareservice':
      return HealthcareServiceBuilder.empty();
    case 'healthcareserviceeligibility':
      return HealthcareServiceEligibilityBuilder.empty();
    case 'healthcareservice_eligibility':
      return HealthcareServiceEligibilityBuilder.empty();
    case 'imagingstudy':
      return ImagingStudyBuilder.empty();
    case 'imagingstudyseries':
      return ImagingStudySeriesBuilder.empty();
    case 'imagingstudy_series':
      return ImagingStudySeriesBuilder.empty();
    case 'imagingstudyperformer':
      return ImagingStudyPerformerBuilder.empty();
    case 'imagingstudy_performer':
      return ImagingStudyPerformerBuilder.empty();
    case 'imagingstudyinstance':
      return ImagingStudyInstanceBuilder.empty();
    case 'imagingstudy_instance':
      return ImagingStudyInstanceBuilder.empty();
    case 'immunization':
      return ImmunizationBuilder.empty();
    case 'immunizationperformer':
      return ImmunizationPerformerBuilder.empty();
    case 'immunization_performer':
      return ImmunizationPerformerBuilder.empty();
    case 'immunizationreaction':
      return ImmunizationReactionBuilder.empty();
    case 'immunization_reaction':
      return ImmunizationReactionBuilder.empty();
    case 'immunizationprotocolapplied':
      return ImmunizationProtocolAppliedBuilder.empty();
    case 'immunization_protocolapplied':
      return ImmunizationProtocolAppliedBuilder.empty();
    case 'immunizationevaluation':
      return ImmunizationEvaluationBuilder.empty();
    case 'immunizationrecommendation':
      return ImmunizationRecommendationBuilder.empty();
    case 'immunizationrecommendationrecommendation':
      return ImmunizationRecommendationRecommendationBuilder.empty();
    case 'immunizationrecommendation_recommendation':
      return ImmunizationRecommendationRecommendationBuilder.empty();
    case 'immunizationrecommendationdatecriterion':
      return ImmunizationRecommendationDateCriterionBuilder.empty();
    case 'immunizationrecommendation_datecriterion':
      return ImmunizationRecommendationDateCriterionBuilder.empty();
    case 'implementationguide':
      return ImplementationGuideBuilder.empty();
    case 'implementationguidedependson':
      return ImplementationGuideDependsOnBuilder.empty();
    case 'implementationguide_dependson':
      return ImplementationGuideDependsOnBuilder.empty();
    case 'implementationguideglobal':
      return ImplementationGuideGlobalBuilder.empty();
    case 'implementationguide_global':
      return ImplementationGuideGlobalBuilder.empty();
    case 'implementationguidedefinition':
      return ImplementationGuideDefinitionBuilder.empty();
    case 'implementationguide_definition':
      return ImplementationGuideDefinitionBuilder.empty();
    case 'implementationguidegrouping':
      return ImplementationGuideGroupingBuilder.empty();
    case 'implementationguide_grouping':
      return ImplementationGuideGroupingBuilder.empty();
    case 'implementationguideresource':
      return ImplementationGuideResourceBuilder.empty();
    case 'implementationguide_resource':
      return ImplementationGuideResourceBuilder.empty();
    case 'implementationguidepage':
      return ImplementationGuidePageBuilder.empty();
    case 'implementationguide_page':
      return ImplementationGuidePageBuilder.empty();
    case 'implementationguideparameter':
      return ImplementationGuideParameterBuilder.empty();
    case 'implementationguide_parameter':
      return ImplementationGuideParameterBuilder.empty();
    case 'implementationguidetemplate':
      return ImplementationGuideTemplateBuilder.empty();
    case 'implementationguide_template':
      return ImplementationGuideTemplateBuilder.empty();
    case 'implementationguidemanifest':
      return ImplementationGuideManifestBuilder.empty();
    case 'implementationguide_manifest':
      return ImplementationGuideManifestBuilder.empty();
    case 'implementationguideresource1':
      return ImplementationGuideResource1Builder.empty();
    case 'implementationguide_resource1':
      return ImplementationGuideResource1Builder.empty();
    case 'implementationguidepage1':
      return ImplementationGuidePage1Builder.empty();
    case 'implementationguide_page1':
      return ImplementationGuidePage1Builder.empty();
    case 'ingredient':
      return IngredientBuilder.empty();
    case 'ingredientmanufacturer':
      return IngredientManufacturerBuilder.empty();
    case 'ingredient_manufacturer':
      return IngredientManufacturerBuilder.empty();
    case 'ingredientsubstance':
      return IngredientSubstanceBuilder.empty();
    case 'ingredient_substance':
      return IngredientSubstanceBuilder.empty();
    case 'ingredientstrength':
      return IngredientStrengthBuilder.empty();
    case 'ingredient_strength':
      return IngredientStrengthBuilder.empty();
    case 'ingredientreferencestrength':
      return IngredientReferenceStrengthBuilder.empty();
    case 'ingredient_referencestrength':
      return IngredientReferenceStrengthBuilder.empty();
    case 'insuranceplan':
      return InsurancePlanBuilder.empty();
    case 'insuranceplancoverage':
      return InsurancePlanCoverageBuilder.empty();
    case 'insuranceplan_coverage':
      return InsurancePlanCoverageBuilder.empty();
    case 'insuranceplanbenefit':
      return InsurancePlanBenefitBuilder.empty();
    case 'insuranceplan_benefit':
      return InsurancePlanBenefitBuilder.empty();
    case 'insuranceplanlimit':
      return InsurancePlanLimitBuilder.empty();
    case 'insuranceplan_limit':
      return InsurancePlanLimitBuilder.empty();
    case 'insuranceplanplan':
      return InsurancePlanPlanBuilder.empty();
    case 'insuranceplan_plan':
      return InsurancePlanPlanBuilder.empty();
    case 'insuranceplangeneralcost':
      return InsurancePlanGeneralCostBuilder.empty();
    case 'insuranceplan_generalcost':
      return InsurancePlanGeneralCostBuilder.empty();
    case 'insuranceplanspecificcost':
      return InsurancePlanSpecificCostBuilder.empty();
    case 'insuranceplan_specificcost':
      return InsurancePlanSpecificCostBuilder.empty();
    case 'insuranceplanbenefit1':
      return InsurancePlanBenefit1Builder.empty();
    case 'insuranceplan_benefit1':
      return InsurancePlanBenefit1Builder.empty();
    case 'insuranceplancost':
      return InsurancePlanCostBuilder.empty();
    case 'insuranceplan_cost':
      return InsurancePlanCostBuilder.empty();
    case 'invoice':
      return InvoiceBuilder.empty();
    case 'invoiceparticipant':
      return InvoiceParticipantBuilder.empty();
    case 'invoice_participant':
      return InvoiceParticipantBuilder.empty();
    case 'invoicelineitem':
      return InvoiceLineItemBuilder.empty();
    case 'invoice_lineitem':
      return InvoiceLineItemBuilder.empty();
    case 'library':
      return LibraryBuilder.empty();
    case 'linkage':
      return LinkageBuilder.empty();
    case 'linkageitem':
      return LinkageItemBuilder.empty();
    case 'linkage_item':
      return LinkageItemBuilder.empty();
    case 'fhirlist':
      return FhirListBuilder.empty();
    case 'list':
      return FhirListBuilder.empty();
    case 'listentry':
      return ListEntryBuilder.empty();
    case 'list_entry':
      return ListEntryBuilder.empty();
    case 'location':
      return LocationBuilder.empty();
    case 'locationposition':
      return LocationPositionBuilder.empty();
    case 'location_position':
      return LocationPositionBuilder.empty();
    case 'manufactureditemdefinition':
      return ManufacturedItemDefinitionBuilder.empty();
    case 'manufactureditemdefinitionproperty':
      return ManufacturedItemDefinitionPropertyBuilder.empty();
    case 'manufactureditemdefinition_property':
      return ManufacturedItemDefinitionPropertyBuilder.empty();
    case 'measure':
      return MeasureBuilder.empty();
    case 'measuregroup':
      return MeasureGroupBuilder.empty();
    case 'measure_group':
      return MeasureGroupBuilder.empty();
    case 'measurepopulation':
      return MeasurePopulationBuilder.empty();
    case 'measure_population':
      return MeasurePopulationBuilder.empty();
    case 'measurestratifier':
      return MeasureStratifierBuilder.empty();
    case 'measure_stratifier':
      return MeasureStratifierBuilder.empty();
    case 'measurecomponent':
      return MeasureComponentBuilder.empty();
    case 'measure_component':
      return MeasureComponentBuilder.empty();
    case 'measuresupplementaldata':
      return MeasureSupplementalDataBuilder.empty();
    case 'measure_supplementaldata':
      return MeasureSupplementalDataBuilder.empty();
    case 'measurereport':
      return MeasureReportBuilder.empty();
    case 'measurereportgroup':
      return MeasureReportGroupBuilder.empty();
    case 'measurereport_group':
      return MeasureReportGroupBuilder.empty();
    case 'measurereportpopulation':
      return MeasureReportPopulationBuilder.empty();
    case 'measurereport_population':
      return MeasureReportPopulationBuilder.empty();
    case 'measurereportstratifier':
      return MeasureReportStratifierBuilder.empty();
    case 'measurereport_stratifier':
      return MeasureReportStratifierBuilder.empty();
    case 'measurereportstratum':
      return MeasureReportStratumBuilder.empty();
    case 'measurereport_stratum':
      return MeasureReportStratumBuilder.empty();
    case 'measurereportcomponent':
      return MeasureReportComponentBuilder.empty();
    case 'measurereport_component':
      return MeasureReportComponentBuilder.empty();
    case 'measurereportpopulation1':
      return MeasureReportPopulation1Builder.empty();
    case 'measurereport_population1':
      return MeasureReportPopulation1Builder.empty();
    case 'medication':
      return MedicationBuilder.empty();
    case 'medicationingredient':
      return MedicationIngredientBuilder.empty();
    case 'medication_ingredient':
      return MedicationIngredientBuilder.empty();
    case 'medicationbatch':
      return MedicationBatchBuilder.empty();
    case 'medication_batch':
      return MedicationBatchBuilder.empty();
    case 'medicationadministration':
      return MedicationAdministrationBuilder.empty();
    case 'medicationadministrationperformer':
      return MedicationAdministrationPerformerBuilder.empty();
    case 'medicationadministration_performer':
      return MedicationAdministrationPerformerBuilder.empty();
    case 'medicationadministrationdosage':
      return MedicationAdministrationDosageBuilder.empty();
    case 'medicationadministration_dosage':
      return MedicationAdministrationDosageBuilder.empty();
    case 'medicationdispense':
      return MedicationDispenseBuilder.empty();
    case 'medicationdispenseperformer':
      return MedicationDispensePerformerBuilder.empty();
    case 'medicationdispense_performer':
      return MedicationDispensePerformerBuilder.empty();
    case 'medicationdispensesubstitution':
      return MedicationDispenseSubstitutionBuilder.empty();
    case 'medicationdispense_substitution':
      return MedicationDispenseSubstitutionBuilder.empty();
    case 'medicationknowledge':
      return MedicationKnowledgeBuilder.empty();
    case 'medicationknowledgerelatedmedicationknowledge':
      return MedicationKnowledgeRelatedMedicationKnowledgeBuilder.empty();
    case 'medicationknowledge_relatedmedicationknowledge':
      return MedicationKnowledgeRelatedMedicationKnowledgeBuilder.empty();
    case 'medicationknowledgemonograph':
      return MedicationKnowledgeMonographBuilder.empty();
    case 'medicationknowledge_monograph':
      return MedicationKnowledgeMonographBuilder.empty();
    case 'medicationknowledgeingredient':
      return MedicationKnowledgeIngredientBuilder.empty();
    case 'medicationknowledge_ingredient':
      return MedicationKnowledgeIngredientBuilder.empty();
    case 'medicationknowledgecost':
      return MedicationKnowledgeCostBuilder.empty();
    case 'medicationknowledge_cost':
      return MedicationKnowledgeCostBuilder.empty();
    case 'medicationknowledgemonitoringprogram':
      return MedicationKnowledgeMonitoringProgramBuilder.empty();
    case 'medicationknowledge_monitoringprogram':
      return MedicationKnowledgeMonitoringProgramBuilder.empty();
    case 'medicationknowledgedosage':
      return MedicationKnowledgeDosageBuilder.empty();
    case 'medicationknowledge_dosage':
      return MedicationKnowledgeDosageBuilder.empty();
    case 'medicationknowledgemedicineclassification':
      return MedicationKnowledgeMedicineClassificationBuilder.empty();
    case 'medicationknowledge_medicineclassification':
      return MedicationKnowledgeMedicineClassificationBuilder.empty();
    case 'medicationknowledgepackaging':
      return MedicationKnowledgePackagingBuilder.empty();
    case 'medicationknowledge_packaging':
      return MedicationKnowledgePackagingBuilder.empty();
    case 'medicationknowledgedrugcharacteristic':
      return MedicationKnowledgeDrugCharacteristicBuilder.empty();
    case 'medicationknowledge_drugcharacteristic':
      return MedicationKnowledgeDrugCharacteristicBuilder.empty();
    case 'medicationknowledgeregulatory':
      return MedicationKnowledgeRegulatoryBuilder.empty();
    case 'medicationknowledge_regulatory':
      return MedicationKnowledgeRegulatoryBuilder.empty();
    case 'medicationknowledgesubstitution':
      return MedicationKnowledgeSubstitutionBuilder.empty();
    case 'medicationknowledge_substitution':
      return MedicationKnowledgeSubstitutionBuilder.empty();
    case 'medicationknowledgemaxdispense':
      return MedicationKnowledgeMaxDispenseBuilder.empty();
    case 'medicationknowledge_maxdispense':
      return MedicationKnowledgeMaxDispenseBuilder.empty();
    case 'medicationrequest':
      return MedicationRequestBuilder.empty();
    case 'medicationrequestdispenserequest':
      return MedicationRequestDispenseRequestBuilder.empty();
    case 'medicationrequest_dispenserequest':
      return MedicationRequestDispenseRequestBuilder.empty();
    case 'medicationrequestinitialfill':
      return MedicationRequestInitialFillBuilder.empty();
    case 'medicationrequest_initialfill':
      return MedicationRequestInitialFillBuilder.empty();
    case 'medicationrequestsubstitution':
      return MedicationRequestSubstitutionBuilder.empty();
    case 'medicationrequest_substitution':
      return MedicationRequestSubstitutionBuilder.empty();
    case 'medicationstatement':
      return MedicationStatementBuilder.empty();
    case 'medicinalproductdefinition':
      return MedicinalProductDefinitionBuilder.empty();
    case 'medicinalproductdefinitioncontact':
      return MedicinalProductDefinitionContactBuilder.empty();
    case 'medicinalproductdefinition_contact':
      return MedicinalProductDefinitionContactBuilder.empty();
    case 'medicinalproductdefinitionname':
      return MedicinalProductDefinitionNameBuilder.empty();
    case 'medicinalproductdefinition_name':
      return MedicinalProductDefinitionNameBuilder.empty();
    case 'medicinalproductdefinitioncrossreference':
      return MedicinalProductDefinitionCrossReferenceBuilder.empty();
    case 'medicinalproductdefinition_crossreference':
      return MedicinalProductDefinitionCrossReferenceBuilder.empty();
    case 'medicinalproductdefinitionoperation':
      return MedicinalProductDefinitionOperationBuilder.empty();
    case 'medicinalproductdefinition_operation':
      return MedicinalProductDefinitionOperationBuilder.empty();
    case 'medicinalproductdefinitioncharacteristic':
      return MedicinalProductDefinitionCharacteristicBuilder.empty();
    case 'medicinalproductdefinition_characteristic':
      return MedicinalProductDefinitionCharacteristicBuilder.empty();
    case 'messagedefinition':
      return MessageDefinitionBuilder.empty();
    case 'messagedefinitionfocus':
      return MessageDefinitionFocusBuilder.empty();
    case 'messagedefinition_focus':
      return MessageDefinitionFocusBuilder.empty();
    case 'messagedefinitionallowedresponse':
      return MessageDefinitionAllowedResponseBuilder.empty();
    case 'messagedefinition_allowedresponse':
      return MessageDefinitionAllowedResponseBuilder.empty();
    case 'messageheader':
      return MessageHeaderBuilder.empty();
    case 'messageheaderdestination':
      return MessageHeaderDestinationBuilder.empty();
    case 'messageheader_destination':
      return MessageHeaderDestinationBuilder.empty();
    case 'messageheadersource':
      return MessageHeaderSourceBuilder.empty();
    case 'messageheader_source':
      return MessageHeaderSourceBuilder.empty();
    case 'messageheaderresponse':
      return MessageHeaderResponseBuilder.empty();
    case 'messageheader_response':
      return MessageHeaderResponseBuilder.empty();
    case 'molecularsequence':
      return MolecularSequenceBuilder.empty();
    case 'namingsystem':
      return NamingSystemBuilder.empty();
    case 'namingsystemuniqueid':
      return NamingSystemUniqueIdBuilder.empty();
    case 'namingsystem_uniqueid':
      return NamingSystemUniqueIdBuilder.empty();
    case 'nutritionorder':
      return NutritionOrderBuilder.empty();
    case 'nutritionorderoraldiet':
      return NutritionOrderOralDietBuilder.empty();
    case 'nutritionorder_oraldiet':
      return NutritionOrderOralDietBuilder.empty();
    case 'nutritionordernutrient':
      return NutritionOrderNutrientBuilder.empty();
    case 'nutritionorder_nutrient':
      return NutritionOrderNutrientBuilder.empty();
    case 'nutritionordertexture':
      return NutritionOrderTextureBuilder.empty();
    case 'nutritionorder_texture':
      return NutritionOrderTextureBuilder.empty();
    case 'nutritionordersupplement':
      return NutritionOrderSupplementBuilder.empty();
    case 'nutritionorder_supplement':
      return NutritionOrderSupplementBuilder.empty();
    case 'nutritionorderenteralformula':
      return NutritionOrderEnteralFormulaBuilder.empty();
    case 'nutritionorder_enteralformula':
      return NutritionOrderEnteralFormulaBuilder.empty();
    case 'nutritionorderadministration':
      return NutritionOrderAdministrationBuilder.empty();
    case 'nutritionorder_administration':
      return NutritionOrderAdministrationBuilder.empty();
    case 'nutritionproduct':
      return NutritionProductBuilder.empty();
    case 'nutritionproductnutrient':
      return NutritionProductNutrientBuilder.empty();
    case 'nutritionproduct_nutrient':
      return NutritionProductNutrientBuilder.empty();
    case 'nutritionproductingredient':
      return NutritionProductIngredientBuilder.empty();
    case 'nutritionproduct_ingredient':
      return NutritionProductIngredientBuilder.empty();
    case 'nutritionproductinstance':
      return NutritionProductInstanceBuilder.empty();
    case 'nutritionproduct_instance':
      return NutritionProductInstanceBuilder.empty();
    case 'observation':
      return ObservationBuilder.empty();
    case 'observationreferencerange':
      return ObservationReferenceRangeBuilder.empty();
    case 'observation_referencerange':
      return ObservationReferenceRangeBuilder.empty();
    case 'observationcomponent':
      return ObservationComponentBuilder.empty();
    case 'observation_component':
      return ObservationComponentBuilder.empty();
    case 'observationdefinition':
      return ObservationDefinitionBuilder.empty();
    case 'operationdefinition':
      return OperationDefinitionBuilder.empty();
    case 'operationdefinitionparameter':
      return OperationDefinitionParameterBuilder.empty();
    case 'operationdefinition_parameter':
      return OperationDefinitionParameterBuilder.empty();
    case 'operationdefinitionbinding':
      return OperationDefinitionBindingBuilder.empty();
    case 'operationdefinition_binding':
      return OperationDefinitionBindingBuilder.empty();
    case 'operationdefinitionreferencedfrom':
      return OperationDefinitionReferencedFromBuilder.empty();
    case 'operationdefinition_referencedfrom':
      return OperationDefinitionReferencedFromBuilder.empty();
    case 'operationdefinitionoverload':
      return OperationDefinitionOverloadBuilder.empty();
    case 'operationdefinition_overload':
      return OperationDefinitionOverloadBuilder.empty();
    case 'operationoutcome':
      return OperationOutcomeBuilder.empty();
    case 'operationoutcomeissue':
      return OperationOutcomeIssueBuilder.empty();
    case 'operationoutcome_issue':
      return OperationOutcomeIssueBuilder.empty();
    case 'organization':
      return OrganizationBuilder.empty();
    case 'organizationaffiliation':
      return OrganizationAffiliationBuilder.empty();
    case 'packagedproductdefinition':
      return PackagedProductDefinitionBuilder.empty();
    case 'packagedproductdefinitionlegalstatusofsupply':
      return PackagedProductDefinitionLegalStatusOfSupplyBuilder.empty();
    case 'packagedproductdefinition_legalstatusofsupply':
      return PackagedProductDefinitionLegalStatusOfSupplyBuilder.empty();
    case 'packagedproductdefinitionproperty':
      return PackagedProductDefinitionPropertyBuilder.empty();
    case 'packagedproductdefinition_property':
      return PackagedProductDefinitionPropertyBuilder.empty();
    case 'packagedproductdefinitioncontaineditem':
      return PackagedProductDefinitionContainedItemBuilder.empty();
    case 'packagedproductdefinition_containeditem':
      return PackagedProductDefinitionContainedItemBuilder.empty();
    case 'parameters':
      return ParametersBuilder.empty();
    case 'parametersparameter':
      return ParametersParameterBuilder.empty();
    case 'parameters_parameter':
      return ParametersParameterBuilder.empty();
    case 'patient':
      return PatientBuilder.empty();
    case 'patientcontact':
      return PatientContactBuilder.empty();
    case 'patient_contact':
      return PatientContactBuilder.empty();
    case 'patientcommunication':
      return PatientCommunicationBuilder.empty();
    case 'patient_communication':
      return PatientCommunicationBuilder.empty();
    case 'patientlink':
      return PatientLinkBuilder.empty();
    case 'patient_link':
      return PatientLinkBuilder.empty();
    case 'paymentnotice':
      return PaymentNoticeBuilder.empty();
    case 'paymentreconciliation':
      return PaymentReconciliationBuilder.empty();
    case 'paymentreconciliationprocessnote':
      return PaymentReconciliationProcessNoteBuilder.empty();
    case 'paymentreconciliation_processnote':
      return PaymentReconciliationProcessNoteBuilder.empty();
    case 'person':
      return PersonBuilder.empty();
    case 'personlink':
      return PersonLinkBuilder.empty();
    case 'person_link':
      return PersonLinkBuilder.empty();
    case 'plandefinition':
      return PlanDefinitionBuilder.empty();
    case 'plandefinitiongoal':
      return PlanDefinitionGoalBuilder.empty();
    case 'plandefinition_goal':
      return PlanDefinitionGoalBuilder.empty();
    case 'plandefinitiontarget':
      return PlanDefinitionTargetBuilder.empty();
    case 'plandefinition_target':
      return PlanDefinitionTargetBuilder.empty();
    case 'plandefinitionaction':
      return PlanDefinitionActionBuilder.empty();
    case 'plandefinition_action':
      return PlanDefinitionActionBuilder.empty();
    case 'plandefinitioncondition':
      return PlanDefinitionConditionBuilder.empty();
    case 'plandefinition_condition':
      return PlanDefinitionConditionBuilder.empty();
    case 'plandefinitionrelatedaction':
      return PlanDefinitionRelatedActionBuilder.empty();
    case 'plandefinition_relatedaction':
      return PlanDefinitionRelatedActionBuilder.empty();
    case 'plandefinitionparticipant':
      return PlanDefinitionParticipantBuilder.empty();
    case 'plandefinition_participant':
      return PlanDefinitionParticipantBuilder.empty();
    case 'plandefinitiondynamicvalue':
      return PlanDefinitionDynamicValueBuilder.empty();
    case 'plandefinition_dynamicvalue':
      return PlanDefinitionDynamicValueBuilder.empty();
    case 'practitioner':
      return PractitionerBuilder.empty();
    case 'practitionerqualification':
      return PractitionerQualificationBuilder.empty();
    case 'practitioner_qualification':
      return PractitionerQualificationBuilder.empty();
    case 'practitionerrole':
      return PractitionerRoleBuilder.empty();
    case 'procedure':
      return ProcedureBuilder.empty();
    case 'procedureperformer':
      return ProcedurePerformerBuilder.empty();
    case 'procedure_performer':
      return ProcedurePerformerBuilder.empty();
    case 'procedurefocaldevice':
      return ProcedureFocalDeviceBuilder.empty();
    case 'procedure_focaldevice':
      return ProcedureFocalDeviceBuilder.empty();
    case 'provenance':
      return ProvenanceBuilder.empty();
    case 'provenanceagent':
      return ProvenanceAgentBuilder.empty();
    case 'provenance_agent':
      return ProvenanceAgentBuilder.empty();
    case 'provenanceentity':
      return ProvenanceEntityBuilder.empty();
    case 'provenance_entity':
      return ProvenanceEntityBuilder.empty();
    case 'questionnaire':
      return QuestionnaireBuilder.empty();
    case 'questionnaireitem':
      return QuestionnaireItemBuilder.empty();
    case 'questionnaire_item':
      return QuestionnaireItemBuilder.empty();
    case 'questionnaireenablewhen':
      return QuestionnaireEnableWhenBuilder.empty();
    case 'questionnaire_enablewhen':
      return QuestionnaireEnableWhenBuilder.empty();
    case 'questionnaireansweroption':
      return QuestionnaireAnswerOptionBuilder.empty();
    case 'questionnaire_answeroption':
      return QuestionnaireAnswerOptionBuilder.empty();
    case 'questionnaireinitial':
      return QuestionnaireInitialBuilder.empty();
    case 'questionnaire_initial':
      return QuestionnaireInitialBuilder.empty();
    case 'questionnaireresponse':
      return QuestionnaireResponseBuilder.empty();
    case 'questionnaireresponseitem':
      return QuestionnaireResponseItemBuilder.empty();
    case 'questionnaireresponse_item':
      return QuestionnaireResponseItemBuilder.empty();
    case 'questionnaireresponseanswer':
      return QuestionnaireResponseAnswerBuilder.empty();
    case 'questionnaireresponse_answer':
      return QuestionnaireResponseAnswerBuilder.empty();
    case 'regulatedauthorization':
      return RegulatedAuthorizationBuilder.empty();
    case 'regulatedauthorizationcase':
      return RegulatedAuthorizationCaseBuilder.empty();
    case 'regulatedauthorization_case':
      return RegulatedAuthorizationCaseBuilder.empty();
    case 'relatedperson':
      return RelatedPersonBuilder.empty();
    case 'relatedpersoncommunication':
      return RelatedPersonCommunicationBuilder.empty();
    case 'relatedperson_communication':
      return RelatedPersonCommunicationBuilder.empty();
    case 'researchstudy':
      return ResearchStudyBuilder.empty();
    case 'researchstudyobjective':
      return ResearchStudyObjectiveBuilder.empty();
    case 'researchstudy_objective':
      return ResearchStudyObjectiveBuilder.empty();
    case 'researchsubject':
      return ResearchSubjectBuilder.empty();
    case 'riskassessment':
      return RiskAssessmentBuilder.empty();
    case 'riskassessmentprediction':
      return RiskAssessmentPredictionBuilder.empty();
    case 'riskassessment_prediction':
      return RiskAssessmentPredictionBuilder.empty();
    case 'schedule':
      return ScheduleBuilder.empty();
    case 'searchparameter':
      return SearchParameterBuilder.empty();
    case 'searchparametercomponent':
      return SearchParameterComponentBuilder.empty();
    case 'searchparameter_component':
      return SearchParameterComponentBuilder.empty();
    case 'servicerequest':
      return ServiceRequestBuilder.empty();
    case 'slot':
      return SlotBuilder.empty();
    case 'specimen':
      return SpecimenBuilder.empty();
    case 'specimencollection':
      return SpecimenCollectionBuilder.empty();
    case 'specimen_collection':
      return SpecimenCollectionBuilder.empty();
    case 'specimenprocessing':
      return SpecimenProcessingBuilder.empty();
    case 'specimen_processing':
      return SpecimenProcessingBuilder.empty();
    case 'specimencontainer':
      return SpecimenContainerBuilder.empty();
    case 'specimen_container':
      return SpecimenContainerBuilder.empty();
    case 'specimendefinition':
      return SpecimenDefinitionBuilder.empty();
    case 'specimendefinitiontypetested':
      return SpecimenDefinitionTypeTestedBuilder.empty();
    case 'specimendefinition_typetested':
      return SpecimenDefinitionTypeTestedBuilder.empty();
    case 'specimendefinitioncontainer':
      return SpecimenDefinitionContainerBuilder.empty();
    case 'specimendefinition_container':
      return SpecimenDefinitionContainerBuilder.empty();
    case 'specimendefinitionadditive':
      return SpecimenDefinitionAdditiveBuilder.empty();
    case 'specimendefinition_additive':
      return SpecimenDefinitionAdditiveBuilder.empty();
    case 'specimendefinitionhandling':
      return SpecimenDefinitionHandlingBuilder.empty();
    case 'specimendefinition_handling':
      return SpecimenDefinitionHandlingBuilder.empty();
    case 'structuredefinition':
      return StructureDefinitionBuilder.empty();
    case 'structuredefinitionmapping':
      return StructureDefinitionMappingBuilder.empty();
    case 'structuredefinition_mapping':
      return StructureDefinitionMappingBuilder.empty();
    case 'structuredefinitioncontext':
      return StructureDefinitionContextBuilder.empty();
    case 'structuredefinition_context':
      return StructureDefinitionContextBuilder.empty();
    case 'structuredefinitionsnapshot':
      return StructureDefinitionSnapshotBuilder.empty();
    case 'structuredefinition_snapshot':
      return StructureDefinitionSnapshotBuilder.empty();
    case 'structuredefinitiondifferential':
      return StructureDefinitionDifferentialBuilder.empty();
    case 'structuredefinition_differential':
      return StructureDefinitionDifferentialBuilder.empty();
    case 'structuremap':
      return StructureMapBuilder.empty();
    case 'structuremapstructure':
      return StructureMapStructureBuilder.empty();
    case 'structuremap_structure':
      return StructureMapStructureBuilder.empty();
    case 'structuremapgroup':
      return StructureMapGroupBuilder.empty();
    case 'structuremap_group':
      return StructureMapGroupBuilder.empty();
    case 'structuremapinput':
      return StructureMapInputBuilder.empty();
    case 'structuremap_input':
      return StructureMapInputBuilder.empty();
    case 'structuremaprule':
      return StructureMapRuleBuilder.empty();
    case 'structuremap_rule':
      return StructureMapRuleBuilder.empty();
    case 'structuremapsource':
      return StructureMapSourceBuilder.empty();
    case 'structuremap_source':
      return StructureMapSourceBuilder.empty();
    case 'structuremaptarget':
      return StructureMapTargetBuilder.empty();
    case 'structuremap_target':
      return StructureMapTargetBuilder.empty();
    case 'structuremapparameter':
      return StructureMapParameterBuilder.empty();
    case 'structuremap_parameter':
      return StructureMapParameterBuilder.empty();
    case 'structuremapdependent':
      return StructureMapDependentBuilder.empty();
    case 'structuremap_dependent':
      return StructureMapDependentBuilder.empty();
    case 'subscription':
      return SubscriptionBuilder.empty();
    case 'subscriptionstatus':
      return SubscriptionStatusBuilder.empty();
    case 'subscriptionstatusnotificationevent':
      return SubscriptionStatusNotificationEventBuilder.empty();
    case 'subscriptionstatus_notificationevent':
      return SubscriptionStatusNotificationEventBuilder.empty();
    case 'subscriptiontopic':
      return SubscriptionTopicBuilder.empty();
    case 'subscriptiontopicresourcetrigger':
      return SubscriptionTopicResourceTriggerBuilder.empty();
    case 'subscriptiontopic_resourcetrigger':
      return SubscriptionTopicResourceTriggerBuilder.empty();
    case 'subscriptiontopicquerycriteria':
      return SubscriptionTopicQueryCriteriaBuilder.empty();
    case 'subscriptiontopic_querycriteria':
      return SubscriptionTopicQueryCriteriaBuilder.empty();
    case 'subscriptiontopiceventtrigger':
      return SubscriptionTopicEventTriggerBuilder.empty();
    case 'subscriptiontopic_eventtrigger':
      return SubscriptionTopicEventTriggerBuilder.empty();
    case 'subscriptiontopiccanfilterby':
      return SubscriptionTopicCanFilterByBuilder.empty();
    case 'subscriptiontopic_canfilterby':
      return SubscriptionTopicCanFilterByBuilder.empty();
    case 'subscriptiontopicnotificationshape':
      return SubscriptionTopicNotificationShapeBuilder.empty();
    case 'subscriptiontopic_notificationshape':
      return SubscriptionTopicNotificationShapeBuilder.empty();
    case 'substance':
      return SubstanceBuilder.empty();
    case 'substanceingredient':
      return SubstanceIngredientBuilder.empty();
    case 'substance_ingredient':
      return SubstanceIngredientBuilder.empty();
    case 'substancedefinition':
      return SubstanceDefinitionBuilder.empty();
    case 'substancedefinitionmoiety':
      return SubstanceDefinitionMoietyBuilder.empty();
    case 'substancedefinition_moiety':
      return SubstanceDefinitionMoietyBuilder.empty();
    case 'substancedefinitionproperty':
      return SubstanceDefinitionPropertyBuilder.empty();
    case 'substancedefinition_property':
      return SubstanceDefinitionPropertyBuilder.empty();
    case 'substancedefinitionmolecularweight':
      return SubstanceDefinitionMolecularWeightBuilder.empty();
    case 'substancedefinition_molecularweight':
      return SubstanceDefinitionMolecularWeightBuilder.empty();
    case 'substancedefinitionstructure':
      return SubstanceDefinitionStructureBuilder.empty();
    case 'substancedefinition_structure':
      return SubstanceDefinitionStructureBuilder.empty();
    case 'substancedefinitionrepresentation':
      return SubstanceDefinitionRepresentationBuilder.empty();
    case 'substancedefinition_representation':
      return SubstanceDefinitionRepresentationBuilder.empty();
    case 'substancedefinitioncode':
      return SubstanceDefinitionCodeBuilder.empty();
    case 'substancedefinition_code':
      return SubstanceDefinitionCodeBuilder.empty();
    case 'substancedefinitionname':
      return SubstanceDefinitionNameBuilder.empty();
    case 'substancedefinition_name':
      return SubstanceDefinitionNameBuilder.empty();
    case 'substancedefinitionofficial':
      return SubstanceDefinitionOfficialBuilder.empty();
    case 'substancedefinition_official':
      return SubstanceDefinitionOfficialBuilder.empty();
    case 'substancedefinitionrelationship':
      return SubstanceDefinitionRelationshipBuilder.empty();
    case 'substancedefinition_relationship':
      return SubstanceDefinitionRelationshipBuilder.empty();
    case 'substancedefinitionsourcematerial':
      return SubstanceDefinitionSourceMaterialBuilder.empty();
    case 'substancedefinition_sourcematerial':
      return SubstanceDefinitionSourceMaterialBuilder.empty();
    case 'supplydelivery':
      return SupplyDeliveryBuilder.empty();
    case 'supplydeliverysupplieditem':
      return SupplyDeliverySuppliedItemBuilder.empty();
    case 'supplydelivery_supplieditem':
      return SupplyDeliverySuppliedItemBuilder.empty();
    case 'supplyrequest':
      return SupplyRequestBuilder.empty();
    case 'supplyrequestparameter':
      return SupplyRequestParameterBuilder.empty();
    case 'supplyrequest_parameter':
      return SupplyRequestParameterBuilder.empty();
    case 'task':
      return TaskBuilder.empty();
    case 'taskrestriction':
      return TaskRestrictionBuilder.empty();
    case 'task_restriction':
      return TaskRestrictionBuilder.empty();
    case 'taskinput':
      return TaskInputBuilder.empty();
    case 'task_input':
      return TaskInputBuilder.empty();
    case 'taskoutput':
      return TaskOutputBuilder.empty();
    case 'task_output':
      return TaskOutputBuilder.empty();
    case 'terminologycapabilities':
      return TerminologyCapabilitiesBuilder.empty();
    case 'terminologycapabilitiessoftware':
      return TerminologyCapabilitiesSoftwareBuilder.empty();
    case 'terminologycapabilities_software':
      return TerminologyCapabilitiesSoftwareBuilder.empty();
    case 'terminologycapabilitiesimplementation':
      return TerminologyCapabilitiesImplementationBuilder.empty();
    case 'terminologycapabilities_implementation':
      return TerminologyCapabilitiesImplementationBuilder.empty();
    case 'terminologycapabilitiescodesystem':
      return TerminologyCapabilitiesCodeSystemBuilder.empty();
    case 'terminologycapabilities_codesystem':
      return TerminologyCapabilitiesCodeSystemBuilder.empty();
    case 'terminologycapabilitiesversion':
      return TerminologyCapabilitiesVersionBuilder.empty();
    case 'terminologycapabilities_version':
      return TerminologyCapabilitiesVersionBuilder.empty();
    case 'terminologycapabilitiesfilter':
      return TerminologyCapabilitiesFilterBuilder.empty();
    case 'terminologycapabilities_filter':
      return TerminologyCapabilitiesFilterBuilder.empty();
    case 'terminologycapabilitiesexpansion':
      return TerminologyCapabilitiesExpansionBuilder.empty();
    case 'terminologycapabilities_expansion':
      return TerminologyCapabilitiesExpansionBuilder.empty();
    case 'terminologycapabilitiesparameter':
      return TerminologyCapabilitiesParameterBuilder.empty();
    case 'terminologycapabilities_parameter':
      return TerminologyCapabilitiesParameterBuilder.empty();
    case 'terminologycapabilitiesvalidatecode':
      return TerminologyCapabilitiesValidateCodeBuilder.empty();
    case 'terminologycapabilities_validatecode':
      return TerminologyCapabilitiesValidateCodeBuilder.empty();
    case 'terminologycapabilitiestranslation':
      return TerminologyCapabilitiesTranslationBuilder.empty();
    case 'terminologycapabilities_translation':
      return TerminologyCapabilitiesTranslationBuilder.empty();
    case 'terminologycapabilitiesclosure':
      return TerminologyCapabilitiesClosureBuilder.empty();
    case 'terminologycapabilities_closure':
      return TerminologyCapabilitiesClosureBuilder.empty();
    case 'testreport':
      return TestReportBuilder.empty();
    case 'testreportparticipant':
      return TestReportParticipantBuilder.empty();
    case 'testreport_participant':
      return TestReportParticipantBuilder.empty();
    case 'testreportsetup':
      return TestReportSetupBuilder.empty();
    case 'testreport_setup':
      return TestReportSetupBuilder.empty();
    case 'testreportaction':
      return TestReportActionBuilder.empty();
    case 'testreport_action':
      return TestReportActionBuilder.empty();
    case 'testreportoperation':
      return TestReportOperationBuilder.empty();
    case 'testreport_operation':
      return TestReportOperationBuilder.empty();
    case 'testreportassert':
      return TestReportAssertBuilder.empty();
    case 'testreport_assert':
      return TestReportAssertBuilder.empty();
    case 'testreporttest':
      return TestReportTestBuilder.empty();
    case 'testreport_test':
      return TestReportTestBuilder.empty();
    case 'testreportaction1':
      return TestReportAction1Builder.empty();
    case 'testreport_action1':
      return TestReportAction1Builder.empty();
    case 'testreportteardown':
      return TestReportTeardownBuilder.empty();
    case 'testreport_teardown':
      return TestReportTeardownBuilder.empty();
    case 'testreportaction2':
      return TestReportAction2Builder.empty();
    case 'testreport_action2':
      return TestReportAction2Builder.empty();
    case 'testscript':
      return TestScriptBuilder.empty();
    case 'testscriptorigin':
      return TestScriptOriginBuilder.empty();
    case 'testscript_origin':
      return TestScriptOriginBuilder.empty();
    case 'testscriptdestination':
      return TestScriptDestinationBuilder.empty();
    case 'testscript_destination':
      return TestScriptDestinationBuilder.empty();
    case 'testscriptmetadata':
      return TestScriptMetadataBuilder.empty();
    case 'testscript_metadata':
      return TestScriptMetadataBuilder.empty();
    case 'testscriptlink':
      return TestScriptLinkBuilder.empty();
    case 'testscript_link':
      return TestScriptLinkBuilder.empty();
    case 'testscriptcapability':
      return TestScriptCapabilityBuilder.empty();
    case 'testscript_capability':
      return TestScriptCapabilityBuilder.empty();
    case 'testscriptfixture':
      return TestScriptFixtureBuilder.empty();
    case 'testscript_fixture':
      return TestScriptFixtureBuilder.empty();
    case 'testscriptvariable':
      return TestScriptVariableBuilder.empty();
    case 'testscript_variable':
      return TestScriptVariableBuilder.empty();
    case 'testscriptsetup':
      return TestScriptSetupBuilder.empty();
    case 'testscript_setup':
      return TestScriptSetupBuilder.empty();
    case 'testscriptaction':
      return TestScriptActionBuilder.empty();
    case 'testscript_action':
      return TestScriptActionBuilder.empty();
    case 'testscriptoperation':
      return TestScriptOperationBuilder.empty();
    case 'testscript_operation':
      return TestScriptOperationBuilder.empty();
    case 'testscriptrequestheader':
      return TestScriptRequestHeaderBuilder.empty();
    case 'testscript_requestheader':
      return TestScriptRequestHeaderBuilder.empty();
    case 'testscriptassert':
      return TestScriptAssertBuilder.empty();
    case 'testscript_assert':
      return TestScriptAssertBuilder.empty();
    case 'testscripttest':
      return TestScriptTestBuilder.empty();
    case 'testscript_test':
      return TestScriptTestBuilder.empty();
    case 'testscriptaction1':
      return TestScriptAction1Builder.empty();
    case 'testscript_action1':
      return TestScriptAction1Builder.empty();
    case 'testscriptteardown':
      return TestScriptTeardownBuilder.empty();
    case 'testscript_teardown':
      return TestScriptTeardownBuilder.empty();
    case 'testscriptaction2':
      return TestScriptAction2Builder.empty();
    case 'testscript_action2':
      return TestScriptAction2Builder.empty();
    case 'valueset':
      return ValueSetBuilder.empty();
    case 'valuesetcompose':
      return ValueSetComposeBuilder.empty();
    case 'valueset_compose':
      return ValueSetComposeBuilder.empty();
    case 'valuesetinclude':
      return ValueSetIncludeBuilder.empty();
    case 'valueset_include':
      return ValueSetIncludeBuilder.empty();
    case 'valuesetconcept':
      return ValueSetConceptBuilder.empty();
    case 'valueset_concept':
      return ValueSetConceptBuilder.empty();
    case 'valuesetdesignation':
      return ValueSetDesignationBuilder.empty();
    case 'valueset_designation':
      return ValueSetDesignationBuilder.empty();
    case 'valuesetfilter':
      return ValueSetFilterBuilder.empty();
    case 'valueset_filter':
      return ValueSetFilterBuilder.empty();
    case 'valuesetexpansion':
      return ValueSetExpansionBuilder.empty();
    case 'valueset_expansion':
      return ValueSetExpansionBuilder.empty();
    case 'valuesetparameter':
      return ValueSetParameterBuilder.empty();
    case 'valueset_parameter':
      return ValueSetParameterBuilder.empty();
    case 'valuesetcontains':
      return ValueSetContainsBuilder.empty();
    case 'valueset_contains':
      return ValueSetContainsBuilder.empty();
    case 'verificationresult':
      return VerificationResultBuilder.empty();
    case 'verificationresultprimarysource':
      return VerificationResultPrimarySourceBuilder.empty();
    case 'verificationresult_primarysource':
      return VerificationResultPrimarySourceBuilder.empty();
    case 'verificationresultattestation':
      return VerificationResultAttestationBuilder.empty();
    case 'verificationresult_attestation':
      return VerificationResultAttestationBuilder.empty();
    case 'verificationresultvalidator':
      return VerificationResultValidatorBuilder.empty();
    case 'verificationresult_validator':
      return VerificationResultValidatorBuilder.empty();
    case 'visionprescription':
      return VisionPrescriptionBuilder.empty();
    case 'visionprescriptionlensspecification':
      return VisionPrescriptionLensSpecificationBuilder.empty();
    case 'visionprescription_lensspecification':
      return VisionPrescriptionLensSpecificationBuilder.empty();
    case 'visionprescriptionprism':
      return VisionPrescriptionPrismBuilder.empty();
    case 'visionprescription_prism':
      return VisionPrescriptionPrismBuilder.empty();
    default:
      return null;
  }
}
