/// Type-hierarchy metadata for one core FHIR type, taken from its
/// StructureDefinition in the R6 specification
/// (profiles-types.json / profiles-resources.json).
class FhirTypeInfo {
  /// Constructor
  const FhirTypeInfo({
    required this.name,
    required this.type,
    required this.kind,
    required this.url,
    this.base,
    this.derivation,
    this.isAbstract = false,
  });

  /// StructureDefinition.name (also the map key)
  final String name;

  /// StructureDefinition.type (differs from [name] for constraints,
  /// e.g. SimpleQuantity's type is Quantity)
  final String type;

  /// StructureDefinition.kind: 'primitive-type', 'complex-type', 'resource'
  /// or 'logical'
  final String kind;

  /// Canonical URL of the StructureDefinition
  final String url;

  /// Name of the base type (tail of StructureDefinition.baseDefinition),
  /// null at the hierarchy root
  final String? base;

  /// StructureDefinition.derivation: 'specialization', 'constraint', or null
  /// at the hierarchy root
  final String? derivation;

  /// StructureDefinition.abstract
  final bool isAbstract;
}

/// Hierarchy metadata for every core FHIR type, keyed by type name.
const Map<String, FhirTypeInfo> fhirTypeHierarchy = <String, FhirTypeInfo>{
  'Account': FhirTypeInfo(
    name: 'Account',
    type: 'Account',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Account',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ActivityDefinition': FhirTypeInfo(
    name: 'ActivityDefinition',
    type: 'ActivityDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ActivityDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ActorDefinition': FhirTypeInfo(
    name: 'ActorDefinition',
    type: 'ActorDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ActorDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Address': FhirTypeInfo(
    name: 'Address',
    type: 'Address',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Address',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'AdministrableProductDefinition': FhirTypeInfo(
    name: 'AdministrableProductDefinition',
    type: 'AdministrableProductDefinition',
    kind: 'resource',
    url:
        'http://hl7.org/fhir/StructureDefinition/AdministrableProductDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'AdverseEvent': FhirTypeInfo(
    name: 'AdverseEvent',
    type: 'AdverseEvent',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/AdverseEvent',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Age': FhirTypeInfo(
    name: 'Age',
    type: 'Age',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Age',
    base: 'Quantity',
    derivation: 'specialization',
  ),
  'AllergyIntolerance': FhirTypeInfo(
    name: 'AllergyIntolerance',
    type: 'AllergyIntolerance',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/AllergyIntolerance',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Annotation': FhirTypeInfo(
    name: 'Annotation',
    type: 'Annotation',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Annotation',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Appointment': FhirTypeInfo(
    name: 'Appointment',
    type: 'Appointment',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Appointment',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'AppointmentResponse': FhirTypeInfo(
    name: 'AppointmentResponse',
    type: 'AppointmentResponse',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/AppointmentResponse',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ArtifactAssessment': FhirTypeInfo(
    name: 'ArtifactAssessment',
    type: 'ArtifactAssessment',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ArtifactAssessment',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Attachment': FhirTypeInfo(
    name: 'Attachment',
    type: 'Attachment',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Attachment',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'AuditEvent': FhirTypeInfo(
    name: 'AuditEvent',
    type: 'AuditEvent',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/AuditEvent',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Availability': FhirTypeInfo(
    name: 'Availability',
    type: 'Availability',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Availability',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'BackboneElement': FhirTypeInfo(
    name: 'BackboneElement',
    type: 'BackboneElement',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/BackboneElement',
    base: 'Element',
    derivation: 'specialization',
    isAbstract: true,
  ),
  'BackboneType': FhirTypeInfo(
    name: 'BackboneType',
    type: 'BackboneType',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/BackboneType',
    base: 'DataType',
    derivation: 'specialization',
    isAbstract: true,
  ),
  'Base': FhirTypeInfo(
    name: 'Base',
    type: 'Base',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Base',
    isAbstract: true,
  ),
  'Basic': FhirTypeInfo(
    name: 'Basic',
    type: 'Basic',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Basic',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Binary': FhirTypeInfo(
    name: 'Binary',
    type: 'Binary',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Binary',
    base: 'Resource',
    derivation: 'specialization',
  ),
  'BiologicallyDerivedProduct': FhirTypeInfo(
    name: 'BiologicallyDerivedProduct',
    type: 'BiologicallyDerivedProduct',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/BiologicallyDerivedProduct',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'BiologicallyDerivedProductDispense': FhirTypeInfo(
    name: 'BiologicallyDerivedProductDispense',
    type: 'BiologicallyDerivedProductDispense',
    kind: 'resource',
    url:
        'http://hl7.org/fhir/StructureDefinition/BiologicallyDerivedProductDispense',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'BodyStructure': FhirTypeInfo(
    name: 'BodyStructure',
    type: 'BodyStructure',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/BodyStructure',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Bundle': FhirTypeInfo(
    name: 'Bundle',
    type: 'Bundle',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Bundle',
    base: 'Resource',
    derivation: 'specialization',
  ),
  'CanonicalResource': FhirTypeInfo(
    name: 'CanonicalResource',
    type: 'CanonicalResource',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/CanonicalResource',
    base: 'DomainResource',
    derivation: 'specialization',
    isAbstract: true,
  ),
  'CapabilityStatement': FhirTypeInfo(
    name: 'CapabilityStatement',
    type: 'CapabilityStatement',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/CapabilityStatement',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'CarePlan': FhirTypeInfo(
    name: 'CarePlan',
    type: 'CarePlan',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/CarePlan',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'CareTeam': FhirTypeInfo(
    name: 'CareTeam',
    type: 'CareTeam',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/CareTeam',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ChargeItem': FhirTypeInfo(
    name: 'ChargeItem',
    type: 'ChargeItem',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ChargeItem',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ChargeItemDefinition': FhirTypeInfo(
    name: 'ChargeItemDefinition',
    type: 'ChargeItemDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ChargeItemDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Citation': FhirTypeInfo(
    name: 'Citation',
    type: 'Citation',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Citation',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Claim': FhirTypeInfo(
    name: 'Claim',
    type: 'Claim',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Claim',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ClaimResponse': FhirTypeInfo(
    name: 'ClaimResponse',
    type: 'ClaimResponse',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ClaimResponse',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ClinicalAssessment': FhirTypeInfo(
    name: 'ClinicalAssessment',
    type: 'ClinicalAssessment',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ClinicalAssessment',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ClinicalUseDefinition': FhirTypeInfo(
    name: 'ClinicalUseDefinition',
    type: 'ClinicalUseDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ClinicalUseDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'CodeSystem': FhirTypeInfo(
    name: 'CodeSystem',
    type: 'CodeSystem',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/CodeSystem',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'CodeableConcept': FhirTypeInfo(
    name: 'CodeableConcept',
    type: 'CodeableConcept',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/CodeableConcept',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'CodeableReference': FhirTypeInfo(
    name: 'CodeableReference',
    type: 'CodeableReference',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/CodeableReference',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Coding': FhirTypeInfo(
    name: 'Coding',
    type: 'Coding',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Coding',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Communication': FhirTypeInfo(
    name: 'Communication',
    type: 'Communication',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Communication',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'CommunicationRequest': FhirTypeInfo(
    name: 'CommunicationRequest',
    type: 'CommunicationRequest',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/CommunicationRequest',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'CompartmentDefinition': FhirTypeInfo(
    name: 'CompartmentDefinition',
    type: 'CompartmentDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/CompartmentDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Composition': FhirTypeInfo(
    name: 'Composition',
    type: 'Composition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Composition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ConceptMap': FhirTypeInfo(
    name: 'ConceptMap',
    type: 'ConceptMap',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ConceptMap',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Condition': FhirTypeInfo(
    name: 'Condition',
    type: 'Condition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Condition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ConditionDefinition': FhirTypeInfo(
    name: 'ConditionDefinition',
    type: 'ConditionDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ConditionDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Consent': FhirTypeInfo(
    name: 'Consent',
    type: 'Consent',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Consent',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ContactDetail': FhirTypeInfo(
    name: 'ContactDetail',
    type: 'ContactDetail',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/ContactDetail',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'ContactPoint': FhirTypeInfo(
    name: 'ContactPoint',
    type: 'ContactPoint',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/ContactPoint',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Contract': FhirTypeInfo(
    name: 'Contract',
    type: 'Contract',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Contract',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Contributor': FhirTypeInfo(
    name: 'Contributor',
    type: 'Contributor',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Contributor',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Count': FhirTypeInfo(
    name: 'Count',
    type: 'Count',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Count',
    base: 'Quantity',
    derivation: 'specialization',
  ),
  'Coverage': FhirTypeInfo(
    name: 'Coverage',
    type: 'Coverage',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Coverage',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'CoverageEligibilityRequest': FhirTypeInfo(
    name: 'CoverageEligibilityRequest',
    type: 'CoverageEligibilityRequest',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/CoverageEligibilityRequest',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'CoverageEligibilityResponse': FhirTypeInfo(
    name: 'CoverageEligibilityResponse',
    type: 'CoverageEligibilityResponse',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/CoverageEligibilityResponse',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'DataRequirement': FhirTypeInfo(
    name: 'DataRequirement',
    type: 'DataRequirement',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/DataRequirement',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'DataType': FhirTypeInfo(
    name: 'DataType',
    type: 'DataType',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/DataType',
    base: 'Element',
    derivation: 'specialization',
    isAbstract: true,
  ),
  'DetectedIssue': FhirTypeInfo(
    name: 'DetectedIssue',
    type: 'DetectedIssue',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/DetectedIssue',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Device': FhirTypeInfo(
    name: 'Device',
    type: 'Device',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Device',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'DeviceAlert': FhirTypeInfo(
    name: 'DeviceAlert',
    type: 'DeviceAlert',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/DeviceAlert',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'DeviceAssociation': FhirTypeInfo(
    name: 'DeviceAssociation',
    type: 'DeviceAssociation',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/DeviceAssociation',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'DeviceDefinition': FhirTypeInfo(
    name: 'DeviceDefinition',
    type: 'DeviceDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/DeviceDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'DeviceDispense': FhirTypeInfo(
    name: 'DeviceDispense',
    type: 'DeviceDispense',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/DeviceDispense',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'DeviceMetric': FhirTypeInfo(
    name: 'DeviceMetric',
    type: 'DeviceMetric',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/DeviceMetric',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'DeviceRequest': FhirTypeInfo(
    name: 'DeviceRequest',
    type: 'DeviceRequest',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/DeviceRequest',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'DeviceUsage': FhirTypeInfo(
    name: 'DeviceUsage',
    type: 'DeviceUsage',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/DeviceUsage',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'DiagnosticReport': FhirTypeInfo(
    name: 'DiagnosticReport',
    type: 'DiagnosticReport',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/DiagnosticReport',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Distance': FhirTypeInfo(
    name: 'Distance',
    type: 'Distance',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Distance',
    base: 'Quantity',
    derivation: 'specialization',
  ),
  'DocumentReference': FhirTypeInfo(
    name: 'DocumentReference',
    type: 'DocumentReference',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/DocumentReference',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'DomainResource': FhirTypeInfo(
    name: 'DomainResource',
    type: 'DomainResource',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/DomainResource',
    base: 'Resource',
    derivation: 'specialization',
    isAbstract: true,
  ),
  'Dosage': FhirTypeInfo(
    name: 'Dosage',
    type: 'Dosage',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Dosage',
    base: 'BackboneType',
    derivation: 'specialization',
  ),
  'Duration': FhirTypeInfo(
    name: 'Duration',
    type: 'Duration',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Duration',
    base: 'Quantity',
    derivation: 'specialization',
  ),
  'Element': FhirTypeInfo(
    name: 'Element',
    type: 'Element',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Element',
    base: 'Base',
    derivation: 'specialization',
    isAbstract: true,
  ),
  'ElementDefinition': FhirTypeInfo(
    name: 'ElementDefinition',
    type: 'ElementDefinition',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/ElementDefinition',
    base: 'BackboneType',
    derivation: 'specialization',
  ),
  'Encounter': FhirTypeInfo(
    name: 'Encounter',
    type: 'Encounter',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Encounter',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'EncounterHistory': FhirTypeInfo(
    name: 'EncounterHistory',
    type: 'EncounterHistory',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/EncounterHistory',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Endpoint': FhirTypeInfo(
    name: 'Endpoint',
    type: 'Endpoint',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Endpoint',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'EnrollmentRequest': FhirTypeInfo(
    name: 'EnrollmentRequest',
    type: 'EnrollmentRequest',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/EnrollmentRequest',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'EnrollmentResponse': FhirTypeInfo(
    name: 'EnrollmentResponse',
    type: 'EnrollmentResponse',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/EnrollmentResponse',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'EpisodeOfCare': FhirTypeInfo(
    name: 'EpisodeOfCare',
    type: 'EpisodeOfCare',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/EpisodeOfCare',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'EventDefinition': FhirTypeInfo(
    name: 'EventDefinition',
    type: 'EventDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/EventDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Evidence': FhirTypeInfo(
    name: 'Evidence',
    type: 'Evidence',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Evidence',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'EvidenceVariable': FhirTypeInfo(
    name: 'EvidenceVariable',
    type: 'EvidenceVariable',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/EvidenceVariable',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ExampleScenario': FhirTypeInfo(
    name: 'ExampleScenario',
    type: 'ExampleScenario',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ExampleScenario',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ExplanationOfBenefit': FhirTypeInfo(
    name: 'ExplanationOfBenefit',
    type: 'ExplanationOfBenefit',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ExplanationOfBenefit',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Expression': FhirTypeInfo(
    name: 'Expression',
    type: 'Expression',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Expression',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'ExtendedContactDetail': FhirTypeInfo(
    name: 'ExtendedContactDetail',
    type: 'ExtendedContactDetail',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/ExtendedContactDetail',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Extension': FhirTypeInfo(
    name: 'Extension',
    type: 'Extension',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Extension',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'FamilyMemberHistory': FhirTypeInfo(
    name: 'FamilyMemberHistory',
    type: 'FamilyMemberHistory',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/FamilyMemberHistory',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Flag': FhirTypeInfo(
    name: 'Flag',
    type: 'Flag',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Flag',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'FormularyItem': FhirTypeInfo(
    name: 'FormularyItem',
    type: 'FormularyItem',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/FormularyItem',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'GenomicStudy': FhirTypeInfo(
    name: 'GenomicStudy',
    type: 'GenomicStudy',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/GenomicStudy',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Goal': FhirTypeInfo(
    name: 'Goal',
    type: 'Goal',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Goal',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'GraphDefinition': FhirTypeInfo(
    name: 'GraphDefinition',
    type: 'GraphDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/GraphDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Group': FhirTypeInfo(
    name: 'Group',
    type: 'Group',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Group',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'GuidanceResponse': FhirTypeInfo(
    name: 'GuidanceResponse',
    type: 'GuidanceResponse',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/GuidanceResponse',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'HealthcareService': FhirTypeInfo(
    name: 'HealthcareService',
    type: 'HealthcareService',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/HealthcareService',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'HumanName': FhirTypeInfo(
    name: 'HumanName',
    type: 'HumanName',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/HumanName',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Identifier': FhirTypeInfo(
    name: 'Identifier',
    type: 'Identifier',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Identifier',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'ImagingSelection': FhirTypeInfo(
    name: 'ImagingSelection',
    type: 'ImagingSelection',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ImagingSelection',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ImagingStudy': FhirTypeInfo(
    name: 'ImagingStudy',
    type: 'ImagingStudy',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ImagingStudy',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Immunization': FhirTypeInfo(
    name: 'Immunization',
    type: 'Immunization',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Immunization',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ImmunizationEvaluation': FhirTypeInfo(
    name: 'ImmunizationEvaluation',
    type: 'ImmunizationEvaluation',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ImmunizationEvaluation',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ImmunizationRecommendation': FhirTypeInfo(
    name: 'ImmunizationRecommendation',
    type: 'ImmunizationRecommendation',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ImmunizationRecommendation',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ImplementationGuide': FhirTypeInfo(
    name: 'ImplementationGuide',
    type: 'ImplementationGuide',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ImplementationGuide',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Ingredient': FhirTypeInfo(
    name: 'Ingredient',
    type: 'Ingredient',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Ingredient',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'InsurancePlan': FhirTypeInfo(
    name: 'InsurancePlan',
    type: 'InsurancePlan',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/InsurancePlan',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'InsuranceProduct': FhirTypeInfo(
    name: 'InsuranceProduct',
    type: 'InsuranceProduct',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/InsuranceProduct',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'InventoryItem': FhirTypeInfo(
    name: 'InventoryItem',
    type: 'InventoryItem',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/InventoryItem',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'InventoryReport': FhirTypeInfo(
    name: 'InventoryReport',
    type: 'InventoryReport',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/InventoryReport',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Invoice': FhirTypeInfo(
    name: 'Invoice',
    type: 'Invoice',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Invoice',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Library': FhirTypeInfo(
    name: 'Library',
    type: 'Library',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Library',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Linkage': FhirTypeInfo(
    name: 'Linkage',
    type: 'Linkage',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Linkage',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'List': FhirTypeInfo(
    name: 'List',
    type: 'List',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/List',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Location': FhirTypeInfo(
    name: 'Location',
    type: 'Location',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Location',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ManufacturedItemDefinition': FhirTypeInfo(
    name: 'ManufacturedItemDefinition',
    type: 'ManufacturedItemDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ManufacturedItemDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'MarketingStatus': FhirTypeInfo(
    name: 'MarketingStatus',
    type: 'MarketingStatus',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/MarketingStatus',
    base: 'BackboneType',
    derivation: 'specialization',
  ),
  'Measure': FhirTypeInfo(
    name: 'Measure',
    type: 'Measure',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Measure',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'MeasureReport': FhirTypeInfo(
    name: 'MeasureReport',
    type: 'MeasureReport',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/MeasureReport',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Medication': FhirTypeInfo(
    name: 'Medication',
    type: 'Medication',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Medication',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'MedicationAdministration': FhirTypeInfo(
    name: 'MedicationAdministration',
    type: 'MedicationAdministration',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/MedicationAdministration',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'MedicationDispense': FhirTypeInfo(
    name: 'MedicationDispense',
    type: 'MedicationDispense',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/MedicationDispense',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'MedicationKnowledge': FhirTypeInfo(
    name: 'MedicationKnowledge',
    type: 'MedicationKnowledge',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/MedicationKnowledge',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'MedicationRequest': FhirTypeInfo(
    name: 'MedicationRequest',
    type: 'MedicationRequest',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/MedicationRequest',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'MedicationStatement': FhirTypeInfo(
    name: 'MedicationStatement',
    type: 'MedicationStatement',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/MedicationStatement',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'MedicinalProductDefinition': FhirTypeInfo(
    name: 'MedicinalProductDefinition',
    type: 'MedicinalProductDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/MedicinalProductDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'MessageDefinition': FhirTypeInfo(
    name: 'MessageDefinition',
    type: 'MessageDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/MessageDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'MessageHeader': FhirTypeInfo(
    name: 'MessageHeader',
    type: 'MessageHeader',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/MessageHeader',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Meta': FhirTypeInfo(
    name: 'Meta',
    type: 'Meta',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Meta',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'MetadataResource': FhirTypeInfo(
    name: 'MetadataResource',
    type: 'MetadataResource',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/MetadataResource',
    base: 'DomainResource',
    derivation: 'specialization',
    isAbstract: true,
  ),
  'MolecularDefinition': FhirTypeInfo(
    name: 'MolecularDefinition',
    type: 'MolecularDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/MolecularDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'MolecularSequence': FhirTypeInfo(
    name: 'MolecularSequence',
    type: 'MolecularSequence',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/MolecularSequence',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'MonetaryComponent': FhirTypeInfo(
    name: 'MonetaryComponent',
    type: 'MonetaryComponent',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/MonetaryComponent',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Money': FhirTypeInfo(
    name: 'Money',
    type: 'Money',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Money',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'MoneyQuantity': FhirTypeInfo(
    name: 'MoneyQuantity',
    type: 'Quantity',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/MoneyQuantity',
    base: 'Quantity',
    derivation: 'constraint',
  ),
  'NamingSystem': FhirTypeInfo(
    name: 'NamingSystem',
    type: 'NamingSystem',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/NamingSystem',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Narrative': FhirTypeInfo(
    name: 'Narrative',
    type: 'Narrative',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Narrative',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'NutritionIntake': FhirTypeInfo(
    name: 'NutritionIntake',
    type: 'NutritionIntake',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/NutritionIntake',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'NutritionOrder': FhirTypeInfo(
    name: 'NutritionOrder',
    type: 'NutritionOrder',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/NutritionOrder',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'NutritionProduct': FhirTypeInfo(
    name: 'NutritionProduct',
    type: 'NutritionProduct',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/NutritionProduct',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Observation': FhirTypeInfo(
    name: 'Observation',
    type: 'Observation',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Observation',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ObservationDefinition': FhirTypeInfo(
    name: 'ObservationDefinition',
    type: 'ObservationDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ObservationDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'OperationDefinition': FhirTypeInfo(
    name: 'OperationDefinition',
    type: 'OperationDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/OperationDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'OperationOutcome': FhirTypeInfo(
    name: 'OperationOutcome',
    type: 'OperationOutcome',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/OperationOutcome',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Organization': FhirTypeInfo(
    name: 'Organization',
    type: 'Organization',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Organization',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'OrganizationAffiliation': FhirTypeInfo(
    name: 'OrganizationAffiliation',
    type: 'OrganizationAffiliation',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/OrganizationAffiliation',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'PackagedProductDefinition': FhirTypeInfo(
    name: 'PackagedProductDefinition',
    type: 'PackagedProductDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/PackagedProductDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ParameterDefinition': FhirTypeInfo(
    name: 'ParameterDefinition',
    type: 'ParameterDefinition',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/ParameterDefinition',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Parameters': FhirTypeInfo(
    name: 'Parameters',
    type: 'Parameters',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Parameters',
    base: 'Resource',
    derivation: 'specialization',
  ),
  'Patient': FhirTypeInfo(
    name: 'Patient',
    type: 'Patient',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Patient',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'PaymentNotice': FhirTypeInfo(
    name: 'PaymentNotice',
    type: 'PaymentNotice',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/PaymentNotice',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'PaymentReconciliation': FhirTypeInfo(
    name: 'PaymentReconciliation',
    type: 'PaymentReconciliation',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/PaymentReconciliation',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Period': FhirTypeInfo(
    name: 'Period',
    type: 'Period',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Period',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Permission': FhirTypeInfo(
    name: 'Permission',
    type: 'Permission',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Permission',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Person': FhirTypeInfo(
    name: 'Person',
    type: 'Person',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Person',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'PersonalRelationship': FhirTypeInfo(
    name: 'PersonalRelationship',
    type: 'PersonalRelationship',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/PersonalRelationship',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'PlanDefinition': FhirTypeInfo(
    name: 'PlanDefinition',
    type: 'PlanDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/PlanDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Practitioner': FhirTypeInfo(
    name: 'Practitioner',
    type: 'Practitioner',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Practitioner',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'PractitionerRole': FhirTypeInfo(
    name: 'PractitionerRole',
    type: 'PractitionerRole',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/PractitionerRole',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'PrimitiveType': FhirTypeInfo(
    name: 'PrimitiveType',
    type: 'PrimitiveType',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/PrimitiveType',
    base: 'DataType',
    derivation: 'specialization',
    isAbstract: true,
  ),
  'Procedure': FhirTypeInfo(
    name: 'Procedure',
    type: 'Procedure',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Procedure',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ProductShelfLife': FhirTypeInfo(
    name: 'ProductShelfLife',
    type: 'ProductShelfLife',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/ProductShelfLife',
    base: 'BackboneType',
    derivation: 'specialization',
  ),
  'Provenance': FhirTypeInfo(
    name: 'Provenance',
    type: 'Provenance',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Provenance',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Quantity': FhirTypeInfo(
    name: 'Quantity',
    type: 'Quantity',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Quantity',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Questionnaire': FhirTypeInfo(
    name: 'Questionnaire',
    type: 'Questionnaire',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Questionnaire',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'QuestionnaireResponse': FhirTypeInfo(
    name: 'QuestionnaireResponse',
    type: 'QuestionnaireResponse',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Range': FhirTypeInfo(
    name: 'Range',
    type: 'Range',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Range',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Ratio': FhirTypeInfo(
    name: 'Ratio',
    type: 'Ratio',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Ratio',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'RatioRange': FhirTypeInfo(
    name: 'RatioRange',
    type: 'RatioRange',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/RatioRange',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Reference': FhirTypeInfo(
    name: 'Reference',
    type: 'Reference',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Reference',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'RegulatedAuthorization': FhirTypeInfo(
    name: 'RegulatedAuthorization',
    type: 'RegulatedAuthorization',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/RegulatedAuthorization',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'RelatedArtifact': FhirTypeInfo(
    name: 'RelatedArtifact',
    type: 'RelatedArtifact',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/RelatedArtifact',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'RelatedPerson': FhirTypeInfo(
    name: 'RelatedPerson',
    type: 'RelatedPerson',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/RelatedPerson',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'RelativeTime': FhirTypeInfo(
    name: 'RelativeTime',
    type: 'RelativeTime',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/RelativeTime',
    base: 'BackboneType',
    derivation: 'specialization',
  ),
  'RequestOrchestration': FhirTypeInfo(
    name: 'RequestOrchestration',
    type: 'RequestOrchestration',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/RequestOrchestration',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Requirements': FhirTypeInfo(
    name: 'Requirements',
    type: 'Requirements',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Requirements',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ResearchStudy': FhirTypeInfo(
    name: 'ResearchStudy',
    type: 'ResearchStudy',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ResearchStudy',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ResearchSubject': FhirTypeInfo(
    name: 'ResearchSubject',
    type: 'ResearchSubject',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ResearchSubject',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Resource': FhirTypeInfo(
    name: 'Resource',
    type: 'Resource',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Resource',
    base: 'Base',
    derivation: 'specialization',
    isAbstract: true,
  ),
  'RiskAssessment': FhirTypeInfo(
    name: 'RiskAssessment',
    type: 'RiskAssessment',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/RiskAssessment',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'SampledData': FhirTypeInfo(
    name: 'SampledData',
    type: 'SampledData',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/SampledData',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'Schedule': FhirTypeInfo(
    name: 'Schedule',
    type: 'Schedule',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Schedule',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'SearchParameter': FhirTypeInfo(
    name: 'SearchParameter',
    type: 'SearchParameter',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/SearchParameter',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'ServiceRequest': FhirTypeInfo(
    name: 'ServiceRequest',
    type: 'ServiceRequest',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ServiceRequest',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Signature': FhirTypeInfo(
    name: 'Signature',
    type: 'Signature',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Signature',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'SimpleQuantity': FhirTypeInfo(
    name: 'SimpleQuantity',
    type: 'Quantity',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/SimpleQuantity',
    base: 'Quantity',
    derivation: 'constraint',
  ),
  'Slot': FhirTypeInfo(
    name: 'Slot',
    type: 'Slot',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Slot',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Specimen': FhirTypeInfo(
    name: 'Specimen',
    type: 'Specimen',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Specimen',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'SpecimenDefinition': FhirTypeInfo(
    name: 'SpecimenDefinition',
    type: 'SpecimenDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/SpecimenDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'StructureDefinition': FhirTypeInfo(
    name: 'StructureDefinition',
    type: 'StructureDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/StructureDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'StructureMap': FhirTypeInfo(
    name: 'StructureMap',
    type: 'StructureMap',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/StructureMap',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Subscription': FhirTypeInfo(
    name: 'Subscription',
    type: 'Subscription',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Subscription',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'SubscriptionStatus': FhirTypeInfo(
    name: 'SubscriptionStatus',
    type: 'SubscriptionStatus',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/SubscriptionStatus',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'SubscriptionTopic': FhirTypeInfo(
    name: 'SubscriptionTopic',
    type: 'SubscriptionTopic',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/SubscriptionTopic',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Substance': FhirTypeInfo(
    name: 'Substance',
    type: 'Substance',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Substance',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'SubstanceDefinition': FhirTypeInfo(
    name: 'SubstanceDefinition',
    type: 'SubstanceDefinition',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/SubstanceDefinition',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'SubstanceNucleicAcid': FhirTypeInfo(
    name: 'SubstanceNucleicAcid',
    type: 'SubstanceNucleicAcid',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/SubstanceNucleicAcid',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'SubstancePolymer': FhirTypeInfo(
    name: 'SubstancePolymer',
    type: 'SubstancePolymer',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/SubstancePolymer',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'SubstanceProtein': FhirTypeInfo(
    name: 'SubstanceProtein',
    type: 'SubstanceProtein',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/SubstanceProtein',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'SubstanceReferenceInformation': FhirTypeInfo(
    name: 'SubstanceReferenceInformation',
    type: 'SubstanceReferenceInformation',
    kind: 'resource',
    url:
        'http://hl7.org/fhir/StructureDefinition/SubstanceReferenceInformation',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'SubstanceSourceMaterial': FhirTypeInfo(
    name: 'SubstanceSourceMaterial',
    type: 'SubstanceSourceMaterial',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/SubstanceSourceMaterial',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'SupplyDelivery': FhirTypeInfo(
    name: 'SupplyDelivery',
    type: 'SupplyDelivery',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/SupplyDelivery',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'SupplyRequest': FhirTypeInfo(
    name: 'SupplyRequest',
    type: 'SupplyRequest',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/SupplyRequest',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Task': FhirTypeInfo(
    name: 'Task',
    type: 'Task',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Task',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'TerminologyCapabilities': FhirTypeInfo(
    name: 'TerminologyCapabilities',
    type: 'TerminologyCapabilities',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/TerminologyCapabilities',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'TestPlan': FhirTypeInfo(
    name: 'TestPlan',
    type: 'TestPlan',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/TestPlan',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'TestReport': FhirTypeInfo(
    name: 'TestReport',
    type: 'TestReport',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/TestReport',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'TestScript': FhirTypeInfo(
    name: 'TestScript',
    type: 'TestScript',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/TestScript',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'Timing': FhirTypeInfo(
    name: 'Timing',
    type: 'Timing',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/Timing',
    base: 'BackboneType',
    derivation: 'specialization',
  ),
  'Transport': FhirTypeInfo(
    name: 'Transport',
    type: 'Transport',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/Transport',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'TriggerDefinition': FhirTypeInfo(
    name: 'TriggerDefinition',
    type: 'TriggerDefinition',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/TriggerDefinition',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'UsageContext': FhirTypeInfo(
    name: 'UsageContext',
    type: 'UsageContext',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/UsageContext',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'ValueSet': FhirTypeInfo(
    name: 'ValueSet',
    type: 'ValueSet',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/ValueSet',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'VerificationResult': FhirTypeInfo(
    name: 'VerificationResult',
    type: 'VerificationResult',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/VerificationResult',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'VirtualServiceDetail': FhirTypeInfo(
    name: 'VirtualServiceDetail',
    type: 'VirtualServiceDetail',
    kind: 'complex-type',
    url: 'http://hl7.org/fhir/StructureDefinition/VirtualServiceDetail',
    base: 'DataType',
    derivation: 'specialization',
  ),
  'VisionPrescription': FhirTypeInfo(
    name: 'VisionPrescription',
    type: 'VisionPrescription',
    kind: 'resource',
    url: 'http://hl7.org/fhir/StructureDefinition/VisionPrescription',
    base: 'DomainResource',
    derivation: 'specialization',
  ),
  'base64Binary': FhirTypeInfo(
    name: 'base64Binary',
    type: 'base64Binary',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/base64Binary',
    base: 'PrimitiveType',
    derivation: 'specialization',
  ),
  'boolean': FhirTypeInfo(
    name: 'boolean',
    type: 'boolean',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/boolean',
    base: 'PrimitiveType',
    derivation: 'specialization',
  ),
  'canonical': FhirTypeInfo(
    name: 'canonical',
    type: 'canonical',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/canonical',
    base: 'uri',
    derivation: 'specialization',
  ),
  'code': FhirTypeInfo(
    name: 'code',
    type: 'code',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/code',
    base: 'string',
    derivation: 'specialization',
  ),
  'date': FhirTypeInfo(
    name: 'date',
    type: 'date',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/date',
    base: 'PrimitiveType',
    derivation: 'specialization',
  ),
  'dateTime': FhirTypeInfo(
    name: 'dateTime',
    type: 'dateTime',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/dateTime',
    base: 'PrimitiveType',
    derivation: 'specialization',
  ),
  'decimal': FhirTypeInfo(
    name: 'decimal',
    type: 'decimal',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/decimal',
    base: 'PrimitiveType',
    derivation: 'specialization',
  ),
  'id': FhirTypeInfo(
    name: 'id',
    type: 'id',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/id',
    base: 'string',
    derivation: 'specialization',
  ),
  'instant': FhirTypeInfo(
    name: 'instant',
    type: 'instant',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/instant',
    base: 'PrimitiveType',
    derivation: 'specialization',
  ),
  'integer': FhirTypeInfo(
    name: 'integer',
    type: 'integer',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/integer',
    base: 'PrimitiveType',
    derivation: 'specialization',
  ),
  'integer64': FhirTypeInfo(
    name: 'integer64',
    type: 'integer64',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/integer64',
    base: 'PrimitiveType',
    derivation: 'specialization',
  ),
  'markdown': FhirTypeInfo(
    name: 'markdown',
    type: 'markdown',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/markdown',
    base: 'string',
    derivation: 'specialization',
  ),
  'oid': FhirTypeInfo(
    name: 'oid',
    type: 'oid',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/oid',
    base: 'uri',
    derivation: 'specialization',
  ),
  'positiveInt': FhirTypeInfo(
    name: 'positiveInt',
    type: 'positiveInt',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/positiveInt',
    base: 'integer',
    derivation: 'specialization',
  ),
  'string': FhirTypeInfo(
    name: 'string',
    type: 'string',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/string',
    base: 'PrimitiveType',
    derivation: 'specialization',
  ),
  'time': FhirTypeInfo(
    name: 'time',
    type: 'time',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/time',
    base: 'PrimitiveType',
    derivation: 'specialization',
  ),
  'unsignedInt': FhirTypeInfo(
    name: 'unsignedInt',
    type: 'unsignedInt',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/unsignedInt',
    base: 'integer',
    derivation: 'specialization',
  ),
  'uri': FhirTypeInfo(
    name: 'uri',
    type: 'uri',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/uri',
    base: 'PrimitiveType',
    derivation: 'specialization',
  ),
  'url': FhirTypeInfo(
    name: 'url',
    type: 'url',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/url',
    base: 'uri',
    derivation: 'specialization',
  ),
  'uuid': FhirTypeInfo(
    name: 'uuid',
    type: 'uuid',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/uuid',
    base: 'uri',
    derivation: 'specialization',
  ),
  'xhtml': FhirTypeInfo(
    name: 'xhtml',
    type: 'xhtml',
    kind: 'primitive-type',
    url: 'http://hl7.org/fhir/StructureDefinition/xhtml',
    base: 'Element',
    derivation: 'specialization',
  ),
};
