// ignore_for_file: lines_longer_than_80_chars
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated from profiles-resources.json by
// fhir_generator/lib/src/generate_element_summary.dart

/// Which of a resource's top-level elements are summary,
/// mandatory and modifier elements, by JSON name.
///
/// From `ElementDefinition.isSummary`, `.min` and
/// `.isModifier` on the resource's StructureDefinition. A
/// choice element is expanded to its JSON names, one per
/// type (`valueQuantity`, `valueString`, ...). Search
/// 3.1.1.5.8 (`_summary`) and 3.1.1.5.9 (`_elements`) are
/// answered from this.
class ResourceElementSummary {
  /// Creates the three sets for one resource type.
  const ResourceElementSummary({
    required this.summary,
    required this.mandatory,
    required this.modifier,
  });

  /// Elements marked `isSummary`.
  final Set<String> summary;

  /// Elements with `min` of 1 or more.
  final Set<String> mandatory;

  /// Elements marked `isModifier`.
  final Set<String> modifier;
}

/// The summary, mandatory and modifier elements of every
/// resource type, by resource type name.
const Map<String, ResourceElementSummary> resourceElementSummary = {
  'Account': ResourceElementSummary(
    summary: {
      'billingStatus',
      'coverage',
      'covers',
      'description',
      'diagnosis',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'name',
      'owner',
      'procedure',
      'servicePeriod',
      'status',
      'subject',
      'type'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ActivityDefinition': ResourceElementSummary(
    summary: {
      'asNeededBoolean',
      'asNeededCodeableConcept',
      'code',
      'contact',
      'date',
      'description',
      'doNotPerform',
      'effectivePeriod',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'kind',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'doNotPerform', 'implicitRules', 'modifierExtension', 'status'},
  ),
  'ActorDefinition': ResourceElementSummary(
    summary: {
      'contact',
      'date',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'type',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status', 'type'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'AdministrableProductDefinition': ResourceElementSummary(
    summary: {
      'administrableDoseForm',
      'device',
      'formOf',
      'id',
      'identifier',
      'implicitRules',
      'ingredient',
      'meta',
      'modifierExtension',
      'producedFrom',
      'property',
      'routeOfAdministration',
      'status',
      'unitOfPresentation'
    },
    mandatory: {'routeOfAdministration', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'AdverseEvent': ResourceElementSummary(
    summary: {
      'actuality',
      'category',
      'causeDateTime',
      'causePeriod',
      'code',
      'contributingFactor',
      'detected',
      'effectDateTime',
      'effectPeriod',
      'encounter',
      'id',
      'identifier',
      'implicitRules',
      'location',
      'meta',
      'mitigatingAction',
      'modifierExtension',
      'outcome',
      'participant',
      'preventiveAction',
      'recordedDate',
      'recorder',
      'resultingEffect',
      'seriousness',
      'status',
      'study',
      'subject',
      'supportingInfo',
      'suspectEntity'
    },
    mandatory: {'actuality', 'status', 'subject'},
    modifier: {'actuality', 'implicitRules', 'modifierExtension', 'status'},
  ),
  'AllergyIntolerance': ResourceElementSummary(
    summary: {
      'asserter',
      'category',
      'clinicalStatus',
      'code',
      'criticality',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'patient',
      'type',
      'verificationStatus'
    },
    mandatory: {'patient'},
    modifier: {
      'clinicalStatus',
      'implicitRules',
      'modifierExtension',
      'verificationStatus'
    },
  ),
  'Appointment': ResourceElementSummary(
    summary: {
      'appointmentType',
      'cancellationReason',
      'class',
      'end',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'reason',
      'serviceCategory',
      'serviceType',
      'specialty',
      'start',
      'status',
      'subject'
    },
    mandatory: {'participant', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'AppointmentResponse': ResourceElementSummary(
    summary: {
      'actor',
      'appointment',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'participantStatus',
      'participantType',
      'proposedNewTime'
    },
    mandatory: {'appointment', 'participantStatus'},
    modifier: {'implicitRules', 'modifierExtension', 'participantStatus'},
  ),
  'ArtifactAssessment': ResourceElementSummary(
    summary: {
      'artifactCanonical',
      'artifactReference',
      'artifactUri',
      'date',
      'disposition',
      'id',
      'identifier',
      'implicitRules',
      'lastReviewDate',
      'meta',
      'modifierExtension',
      'title',
      'workflowStatus'
    },
    mandatory: {'artifactCanonical', 'artifactReference', 'artifactUri'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'AuditEvent': ResourceElementSummary(
    summary: {
      'action',
      'agent',
      'authorization',
      'entity',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'outcome',
      'patient',
      'recorded',
      'severity',
      'source',
      'subtype',
      'type'
    },
    mandatory: {'agent', 'recorded', 'source', 'type'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'Basic': ResourceElementSummary(
    summary: {
      'author',
      'code',
      'created',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'subject'
    },
    mandatory: {'code'},
    modifier: {'code', 'implicitRules', 'modifierExtension'},
  ),
  'Binary': ResourceElementSummary(
    summary: {'contentType', 'id', 'implicitRules', 'meta', 'securityContext'},
    mandatory: {'contentType'},
    modifier: {'implicitRules'},
  ),
  'BiologicallyDerivedProduct': ResourceElementSummary(
    summary: {
      'biologicalSourceEvent',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'BiologicallyDerivedProductDispense': ResourceElementSummary(
    summary: {'id', 'implicitRules', 'meta', 'modifierExtension'},
    mandatory: {'patient', 'product', 'status'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'BodyStructure': ResourceElementSummary(
    summary: {
      'active',
      'description',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'morphology',
      'patient'
    },
    mandatory: {'includedStructure', 'patient'},
    modifier: {'active', 'implicitRules', 'modifierExtension'},
  ),
  'Bundle': ResourceElementSummary(
    summary: {
      'entry',
      'id',
      'identifier',
      'implicitRules',
      'issues',
      'link',
      'meta',
      'signature',
      'timestamp',
      'total',
      'type'
    },
    mandatory: {'type'},
    modifier: {'implicitRules'},
  ),
  'CapabilityStatement': ResourceElementSummary(
    summary: {
      'acceptLanguage',
      'actorDefinition',
      'contact',
      'date',
      'document',
      'experimental',
      'fhirVersion',
      'format',
      'id',
      'identifier',
      'implementation',
      'implementationGuide',
      'implicitRules',
      'imports',
      'instantiates',
      'jurisdiction',
      'kind',
      'messaging',
      'meta',
      'modifierExtension',
      'name',
      'patchFormat',
      'publisher',
      'rest',
      'software',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'date', 'fhirVersion', 'format', 'kind', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'CarePlan': ResourceElementSummary(
    summary: {
      'addresses',
      'basedOn',
      'category',
      'created',
      'custodian',
      'description',
      'encounter',
      'id',
      'identifier',
      'implicitRules',
      'intent',
      'meta',
      'modifierExtension',
      'partOf',
      'period',
      'replaces',
      'status',
      'subject',
      'title'
    },
    mandatory: {'intent', 'status', 'subject'},
    modifier: {'implicitRules', 'intent', 'modifierExtension', 'status'},
  ),
  'CareTeam': ResourceElementSummary(
    summary: {
      'category',
      'id',
      'identifier',
      'implicitRules',
      'managingOrganization',
      'meta',
      'modifierExtension',
      'name',
      'period',
      'status',
      'subject'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ChargeItem': ResourceElementSummary(
    summary: {
      'account',
      'bodysite',
      'code',
      'encounter',
      'enteredDate',
      'enterer',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'occurrenceDateTime',
      'occurrencePeriod',
      'occurrenceTiming',
      'quantity',
      'status',
      'subject'
    },
    mandatory: {'code', 'status', 'subject'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ChargeItemDefinition': ResourceElementSummary(
    summary: {
      'account',
      'code',
      'contact',
      'date',
      'derivedFromUri',
      'description',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'partOf',
      'publisher',
      'replaces',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Citation': ResourceElementSummary(
    summary: {
      'approvalDate',
      'contact',
      'date',
      'effectivePeriod',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'lastReviewDate',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Claim': ResourceElementSummary(
    summary: {
      'billablePeriod',
      'created',
      'id',
      'implicitRules',
      'insurance',
      'insurer',
      'meta',
      'modifierExtension',
      'patient',
      'priority',
      'provider',
      'status',
      'type',
      'use'
    },
    mandatory: {'created', 'patient', 'status', 'type', 'use'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ClaimResponse': ResourceElementSummary(
    summary: {
      'created',
      'decision',
      'id',
      'implicitRules',
      'insurer',
      'meta',
      'modifierExtension',
      'outcome',
      'patient',
      'request',
      'status',
      'total',
      'type',
      'use'
    },
    mandatory: {'created', 'outcome', 'patient', 'status', 'type', 'use'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ClinicalAssessment': ResourceElementSummary(
    summary: {
      'date',
      'description',
      'effectiveDateTime',
      'effectivePeriod',
      'encounter',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'performer',
      'problem',
      'status',
      'subject'
    },
    mandatory: {'status', 'subject'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ClinicalUseDefinition': ResourceElementSummary(
    summary: {
      'category',
      'contraindication',
      'id',
      'identifier',
      'implicitRules',
      'indication',
      'interaction',
      'library',
      'meta',
      'modifierExtension',
      'population',
      'status',
      'subject',
      'type',
      'undesirableEffect',
      'warning'
    },
    mandatory: {'type'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'CodeSystem': ResourceElementSummary(
    summary: {
      'caseSensitive',
      'compositional',
      'contact',
      'content',
      'count',
      'date',
      'effectivePeriod',
      'experimental',
      'filter',
      'hierarchyMeaning',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'property',
      'publisher',
      'status',
      'supplements',
      'title',
      'url',
      'useContext',
      'valueSet',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString',
      'versionNeeded'
    },
    mandatory: {'content', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Communication': ResourceElementSummary(
    summary: {
      'basedOn',
      'encounter',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'partOf',
      'priority',
      'reason',
      'status',
      'statusReason',
      'subject'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'CommunicationRequest': ResourceElementSummary(
    summary: {
      'authoredOn',
      'basedOn',
      'doNotPerform',
      'encounter',
      'groupIdentifier',
      'id',
      'identifier',
      'implicitRules',
      'informationProvider',
      'intent',
      'meta',
      'modifierExtension',
      'occurrenceDateTime',
      'occurrencePeriod',
      'priority',
      'reason',
      'replaces',
      'requester',
      'status'
    },
    mandatory: {'intent', 'status'},
    modifier: {
      'doNotPerform',
      'implicitRules',
      'intent',
      'modifierExtension',
      'status'
    },
  ),
  'CompartmentDefinition': ResourceElementSummary(
    summary: {
      'code',
      'contact',
      'date',
      'experimental',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'resource',
      'search',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'code', 'name', 'search', 'status', 'url'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Composition': ResourceElementSummary(
    summary: {
      'author',
      'category',
      'custodian',
      'date',
      'encounter',
      'event',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'name',
      'status',
      'subject',
      'title',
      'type',
      'url',
      'useContext',
      'version'
    },
    mandatory: {'author', 'date', 'status', 'title', 'type'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ConceptMap': ResourceElementSummary(
    summary: {
      'additionalAttribute',
      'contact',
      'date',
      'effectivePeriod',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'property',
      'publisher',
      'sourceScopeCanonical',
      'sourceScopeUri',
      'status',
      'targetScopeCanonical',
      'targetScopeUri',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Condition': ResourceElementSummary(
    summary: {
      'asserter',
      'bodySite',
      'clinicalStatus',
      'code',
      'encounter',
      'evidence',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'onsetAge',
      'onsetDateTime',
      'onsetPeriod',
      'onsetRange',
      'onsetString',
      'recordedDate',
      'recorder',
      'subject',
      'verificationStatus'
    },
    mandatory: {'clinicalStatus', 'subject'},
    modifier: {
      'clinicalStatus',
      'implicitRules',
      'modifierExtension',
      'verificationStatus'
    },
  ),
  'ConditionDefinition': ResourceElementSummary(
    summary: {
      'bodySite',
      'code',
      'contact',
      'date',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'severity',
      'stage',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'code', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Consent': ResourceElementSummary(
    summary: {
      'category',
      'date',
      'decision',
      'grantee',
      'grantor',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'period',
      'provision',
      'status',
      'subject',
      'verification'
    },
    mandatory: {'status'},
    modifier: {'decision', 'implicitRules', 'modifierExtension', 'status'},
  ),
  'Contract': ResourceElementSummary(
    summary: {
      'applies',
      'id',
      'identifier',
      'implicitRules',
      'issued',
      'meta',
      'modifierExtension',
      'name',
      'status',
      'subType',
      'subject',
      'title',
      'type',
      'version'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Coverage': ResourceElementSummary(
    summary: {
      'beneficiary',
      'dependent',
      'id',
      'identifier',
      'implicitRules',
      'insurer',
      'kind',
      'meta',
      'modifierExtension',
      'network',
      'order',
      'period',
      'policyHolder',
      'status',
      'subscriber',
      'subscriberId',
      'type'
    },
    mandatory: {'beneficiary', 'kind', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'CoverageEligibilityRequest': ResourceElementSummary(
    summary: {
      'created',
      'id',
      'implicitRules',
      'insurer',
      'meta',
      'modifierExtension',
      'patient',
      'purpose',
      'status'
    },
    mandatory: {'created', 'insurer', 'patient', 'purpose', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'CoverageEligibilityResponse': ResourceElementSummary(
    summary: {
      'created',
      'id',
      'implicitRules',
      'insurer',
      'meta',
      'modifierExtension',
      'outcome',
      'patient',
      'purpose',
      'request',
      'status'
    },
    mandatory: {
      'created',
      'insurer',
      'outcome',
      'patient',
      'purpose',
      'request',
      'status'
    },
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'DetectedIssue': ResourceElementSummary(
    summary: {
      'author',
      'category',
      'code',
      'encounter',
      'id',
      'identifiedDateTime',
      'identifiedPeriod',
      'identifiedTiming',
      'identifier',
      'implicated',
      'implicitRules',
      'meta',
      'modifierExtension',
      'severity',
      'status',
      'subject'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Device': ResourceElementSummary(
    summary: {
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'safety',
      'status',
      'udiCarrier'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'DeviceAlert': ResourceElementSummary(
    summary: {
      'condition',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'priority',
      'status',
      'subject'
    },
    mandatory: {'condition', 'status', 'subject'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'DeviceAssociation': ResourceElementSummary(
    summary: {'id', 'implicitRules', 'meta', 'modifierExtension'},
    mandatory: {'device', 'status'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'DeviceDefinition': ResourceElementSummary(
    summary: {
      'classification',
      'conformsTo',
      'contact',
      'date',
      'deviceName',
      'experimental',
      'hasPart',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'manufacturer',
      'meta',
      'modelNumber',
      'modifierExtension',
      'name',
      'publisher',
      'safety',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'DeviceDispense': ResourceElementSummary(
    summary: {
      'device',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'preparedDate',
      'status',
      'subject'
    },
    mandatory: {'device', 'status', 'subject'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'DeviceMetric': ResourceElementSummary(
    summary: {
      'category',
      'device',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'operationalStatus',
      'type',
      'unit'
    },
    mandatory: {'category', 'device', 'type'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'DeviceRequest': ResourceElementSummary(
    summary: {
      'authoredOn',
      'basedOn',
      'code',
      'doNotPerform',
      'encounter',
      'groupIdentifier',
      'id',
      'identifier',
      'implicitRules',
      'instantiatesCanonical',
      'instantiatesUri',
      'intent',
      'meta',
      'modifierExtension',
      'occurrenceDateTime',
      'occurrencePeriod',
      'occurrenceTiming',
      'performer',
      'priority',
      'reason',
      'replaces',
      'requester',
      'status',
      'subject'
    },
    mandatory: {'code', 'intent', 'subject'},
    modifier: {
      'doNotPerform',
      'implicitRules',
      'intent',
      'modifierExtension',
      'status'
    },
  ),
  'DeviceUsage': ResourceElementSummary(
    summary: {
      'basedOn',
      'bodySite',
      'context',
      'dateAsserted',
      'derivedFrom',
      'device',
      'id',
      'identifier',
      'implicitRules',
      'informationSource',
      'meta',
      'modifierExtension',
      'patient',
      'reason',
      'status',
      'timingDateTime',
      'timingPeriod',
      'timingTiming'
    },
    mandatory: {'device', 'patient', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'DiagnosticReport': ResourceElementSummary(
    summary: {
      'category',
      'code',
      'effectiveDateTime',
      'effectivePeriod',
      'encounter',
      'id',
      'identifier',
      'implicitRules',
      'issued',
      'media',
      'meta',
      'modifierExtension',
      'performer',
      'procedure',
      'recomendation',
      'resultsInterpreter',
      'status',
      'subject'
    },
    mandatory: {'code', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'DocumentReference': ResourceElementSummary(
    summary: {
      'author',
      'bodySite',
      'category',
      'content',
      'context',
      'date',
      'description',
      'docStatus',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modality',
      'modifierExtension',
      'period',
      'relatesTo',
      'securityLabel',
      'status',
      'subject',
      'type',
      'version'
    },
    mandatory: {'content', 'status'},
    modifier: {'docStatus', 'implicitRules', 'modifierExtension', 'status'},
  ),
  'Encounter': ResourceElementSummary(
    summary: {
      'appointment',
      'class',
      'diagnosis',
      'episodeOfCare',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'participant',
      'reason',
      'serviceType',
      'status',
      'subject',
      'type'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'EncounterHistory': ResourceElementSummary(
    summary: {
      'class',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'serviceType',
      'status',
      'subject',
      'type'
    },
    mandatory: {'class', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Endpoint': ResourceElementSummary(
    summary: {
      'address',
      'connectionType',
      'description',
      'environmentType',
      'id',
      'identifier',
      'implicitRules',
      'managingOrganization',
      'meta',
      'modifierExtension',
      'name',
      'period',
      'status'
    },
    mandatory: {'address', 'connectionType', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'EnrollmentRequest': ResourceElementSummary(
    summary: {'id', 'implicitRules', 'meta', 'modifierExtension', 'status'},
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'EnrollmentResponse': ResourceElementSummary(
    summary: {'id', 'implicitRules', 'meta', 'modifierExtension', 'status'},
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'EpisodeOfCare': ResourceElementSummary(
    summary: {
      'diagnosis',
      'id',
      'implicitRules',
      'managingOrganization',
      'meta',
      'modifierExtension',
      'period',
      'reason',
      'status',
      'subject',
      'type'
    },
    mandatory: {'status', 'subject'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'EventDefinition': ResourceElementSummary(
    summary: {
      'approvalDate',
      'contact',
      'date',
      'effectivePeriod',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'lastReviewDate',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'trigger',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status', 'trigger'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Evidence': ResourceElementSummary(
    summary: {
      'author',
      'contact',
      'date',
      'description',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'publisher',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'EvidenceVariable': ResourceElementSummary(
    summary: {
      'contact',
      'date',
      'definition',
      'description',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'shortTitle',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ExampleScenario': ResourceElementSummary(
    summary: {
      'contact',
      'date',
      'description',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ExplanationOfBenefit': ResourceElementSummary(
    summary: {
      'billablePeriod',
      'created',
      'decision',
      'id',
      'implicitRules',
      'insurance',
      'insurer',
      'meta',
      'modifierExtension',
      'outcome',
      'patient',
      'provider',
      'status',
      'total',
      'type',
      'use'
    },
    mandatory: {'created', 'outcome', 'patient', 'status', 'type', 'use'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'FamilyMemberHistory': ResourceElementSummary(
    summary: {
      'ageAge',
      'ageRange',
      'ageString',
      'condition',
      'dataAbsentReason',
      'date',
      'deceasedAge',
      'deceasedBoolean',
      'deceasedDate',
      'deceasedRange',
      'deceasedString',
      'estimatedAge',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'name',
      'participant',
      'patient',
      'reason',
      'relationship',
      'sex',
      'status'
    },
    mandatory: {'patient', 'relationship', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Flag': ResourceElementSummary(
    summary: {
      'author',
      'category',
      'code',
      'encounter',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'period',
      'status',
      'subject'
    },
    mandatory: {'code', 'subject'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'FormularyItem': ResourceElementSummary(
    summary: {
      'code',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'status'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'GenomicStudy': ResourceElementSummary(
    summary: {
      'encounter',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'status',
      'subject',
      'type'
    },
    mandatory: {'status', 'subject'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Goal': ResourceElementSummary(
    summary: {
      'achievementStatus',
      'category',
      'description',
      'id',
      'implicitRules',
      'lifecycleStatus',
      'meta',
      'modifierExtension',
      'priority',
      'source',
      'startCodeableConcept',
      'startDate',
      'statusDate',
      'subject'
    },
    mandatory: {'description', 'lifecycleStatus', 'subject'},
    modifier: {'implicitRules', 'lifecycleStatus', 'modifierExtension'},
  ),
  'GraphDefinition': ResourceElementSummary(
    summary: {
      'contact',
      'date',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'name', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Group': ResourceElementSummary(
    summary: {
      'characteristic',
      'code',
      'combinationMethod',
      'contact',
      'date',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'managingEntity',
      'membership',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'quantity',
      'status',
      'title',
      'type',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'membership'},
    modifier: {
      'combinationMethod',
      'implicitRules',
      'modifierExtension',
      'status'
    },
  ),
  'GuidanceResponse': ResourceElementSummary(
    summary: {
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'moduleCanonical',
      'moduleCodeableConcept',
      'moduleUri',
      'requestIdentifier',
      'status'
    },
    mandatory: {
      'moduleCanonical',
      'moduleCodeableConcept',
      'moduleUri',
      'status'
    },
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'HealthcareService': ResourceElementSummary(
    summary: {
      'active',
      'category',
      'comment',
      'id',
      'identifier',
      'implicitRules',
      'location',
      'meta',
      'modifierExtension',
      'name',
      'photo',
      'providedBy',
      'specialty',
      'type'
    },
    mandatory: {},
    modifier: {'active', 'implicitRules', 'modifierExtension'},
  ),
  'ImagingSelection': ResourceElementSummary(
    summary: {
      'basedOn',
      'bodySite',
      'category',
      'code',
      'derivedFrom',
      'endpoint',
      'focus',
      'frameOfReferenceUid',
      'id',
      'identifier',
      'implicitRules',
      'instance',
      'issued',
      'meta',
      'modifierExtension',
      'performer',
      'seriesNumber',
      'seriesUid',
      'status',
      'studyUid',
      'subject'
    },
    mandatory: {'code', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ImagingStudy': ResourceElementSummary(
    summary: {
      'basedOn',
      'description',
      'encounter',
      'endpoint',
      'id',
      'identifier',
      'implicitRules',
      'location',
      'meta',
      'modality',
      'modifierExtension',
      'note',
      'numberOfInstances',
      'numberOfSeries',
      'partOf',
      'procedure',
      'reason',
      'referrer',
      'series',
      'started',
      'status',
      'subject'
    },
    mandatory: {'status', 'subject'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Immunization': ResourceElementSummary(
    summary: {
      'basedOn',
      'id',
      'implicitRules',
      'isSubpotent',
      'meta',
      'modifierExtension',
      'note',
      'occurrenceDateTime',
      'occurrenceString',
      'patient',
      'performer',
      'primarySource',
      'status',
      'vaccineCode'
    },
    mandatory: {
      'occurrenceDateTime',
      'occurrenceString',
      'patient',
      'status',
      'vaccineCode'
    },
    modifier: {'implicitRules', 'isSubpotent', 'modifierExtension', 'status'},
  ),
  'ImmunizationEvaluation': ResourceElementSummary(
    summary: {
      'doseStatus',
      'id',
      'immunizationEvent',
      'implicitRules',
      'meta',
      'modifierExtension',
      'patient',
      'status',
      'targetDisease'
    },
    mandatory: {
      'doseStatus',
      'immunizationEvent',
      'patient',
      'status',
      'targetDisease'
    },
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ImmunizationRecommendation': ResourceElementSummary(
    summary: {
      'date',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'patient',
      'recommendation'
    },
    mandatory: {'date', 'patient', 'recommendation'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'ImplementationGuide': ResourceElementSummary(
    summary: {
      'contact',
      'date',
      'dependsOn',
      'experimental',
      'fhirVersion',
      'global',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'license',
      'meta',
      'modifierExtension',
      'name',
      'packageId',
      'publisher',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'fhirVersion', 'name', 'packageId', 'status', 'url'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Ingredient': ResourceElementSummary(
    summary: {
      'allergenicIndicator',
      'for',
      'function',
      'group',
      'id',
      'identifier',
      'implicitRules',
      'manufacturer',
      'meta',
      'modifierExtension',
      'role',
      'status',
      'substance'
    },
    mandatory: {'role', 'status', 'substance'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'InsurancePlan': ResourceElementSummary(
    summary: {
      'coverageArea',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'product'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'InsuranceProduct': ResourceElementSummary(
    summary: {
      'administeredBy',
      'coverageArea',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'name',
      'ownedBy',
      'status',
      'type'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'InventoryItem': ResourceElementSummary(
    summary: {
      'baseUnit',
      'category',
      'code',
      'id',
      'identifier',
      'implicitRules',
      'inventoryStatus',
      'meta',
      'modifierExtension',
      'name',
      'netContent',
      'status'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'InventoryReport': ResourceElementSummary(
    summary: {
      'countType',
      'id',
      'identifier',
      'implicitRules',
      'inventoryListing',
      'meta',
      'modifierExtension',
      'operationType',
      'operationTypeReason',
      'reportedDateTime',
      'status'
    },
    mandatory: {'countType', 'reportedDateTime', 'status'},
    modifier: {'countType', 'implicitRules', 'modifierExtension', 'status'},
  ),
  'Invoice': ResourceElementSummary(
    summary: {
      'creation',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'periodDate',
      'periodPeriod',
      'recipient',
      'status',
      'subject',
      'totalGross',
      'totalNet',
      'type'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Library': ResourceElementSummary(
    summary: {
      'contact',
      'content',
      'date',
      'description',
      'effectivePeriod',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'type',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status', 'type'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Linkage': ResourceElementSummary(
    summary: {
      'active',
      'author',
      'id',
      'implicitRules',
      'item',
      'meta',
      'modifierExtension'
    },
    mandatory: {'item'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'List': ResourceElementSummary(
    summary: {
      'code',
      'date',
      'id',
      'implicitRules',
      'meta',
      'mode',
      'modifierExtension',
      'source',
      'status',
      'subject',
      'title'
    },
    mandatory: {'mode', 'status'},
    modifier: {'implicitRules', 'mode', 'modifierExtension', 'status'},
  ),
  'Location': ResourceElementSummary(
    summary: {
      'description',
      'form',
      'id',
      'identifier',
      'implicitRules',
      'managingOrganization',
      'meta',
      'mode',
      'modifierExtension',
      'name',
      'operationalStatus',
      'status',
      'type'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ManufacturedItemDefinition': ResourceElementSummary(
    summary: {
      'component',
      'id',
      'identifier',
      'implicitRules',
      'ingredient',
      'manufacturedDoseForm',
      'manufacturer',
      'marketingStatus',
      'meta',
      'modifierExtension',
      'name',
      'property',
      'status',
      'unitOfPresentation'
    },
    mandatory: {'manufacturedDoseForm', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Measure': ResourceElementSummary(
    summary: {
      'basis',
      'clinicalRecommendationStatement',
      'compositeScoring',
      'contact',
      'date',
      'description',
      'disclaimer',
      'effectivePeriod',
      'experimental',
      'guidance',
      'id',
      'identifier',
      'implicitRules',
      'improvementNotation',
      'improvementNotationGuidance',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'rateAggregation',
      'rationale',
      'riskAdjustment',
      'scoring',
      'scoringPrecision',
      'scoringUnit',
      'status',
      'title',
      'type',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'MeasureReport': ResourceElementSummary(
    summary: {
      'dataUpdateType',
      'date',
      'id',
      'identifier',
      'implicitRules',
      'improvementNotation',
      'measure',
      'meta',
      'modifierExtension',
      'period',
      'reporter',
      'scoring',
      'status',
      'subject',
      'type'
    },
    mandatory: {'period', 'status', 'type'},
    modifier: {
      'dataUpdateType',
      'implicitRules',
      'improvementNotation',
      'modifierExtension',
      'scoring',
      'status'
    },
  ),
  'Medication': ResourceElementSummary(
    summary: {
      'code',
      'id',
      'identifier',
      'implicitRules',
      'marketingAuthorizationHolder',
      'meta',
      'modifierExtension',
      'status',
      'totalVolume'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'MedicationAdministration': ResourceElementSummary(
    summary: {
      'id',
      'implicitRules',
      'medication',
      'meta',
      'modifierExtension',
      'occurrenceDateTime',
      'occurrencePeriod',
      'occurrenceTiming',
      'partOf',
      'performer',
      'recorded',
      'status',
      'subject'
    },
    mandatory: {
      'medication',
      'occurrenceDateTime',
      'occurrencePeriod',
      'occurrenceTiming',
      'status',
      'subject'
    },
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'MedicationDispense': ResourceElementSummary(
    summary: {
      'id',
      'implicitRules',
      'medication',
      'meta',
      'modifierExtension',
      'status',
      'subject',
      'whenPrepared'
    },
    mandatory: {'medication', 'status', 'subject'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'MedicationKnowledge': ResourceElementSummary(
    summary: {
      'code',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'monitoringProgram',
      'name',
      'status'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'MedicationRequest': ResourceElementSummary(
    summary: {
      'authoredOn',
      'basedOn',
      'doNotPerform',
      'groupIdentifier',
      'id',
      'implicitRules',
      'intent',
      'medication',
      'meta',
      'modifierExtension',
      'performerType',
      'priority',
      'reported',
      'requester',
      'status',
      'subject'
    },
    mandatory: {'intent', 'medication', 'status', 'subject'},
    modifier: {
      'doNotPerform',
      'implicitRules',
      'intent',
      'modifierExtension',
      'status'
    },
  ),
  'MedicationStatement': ResourceElementSummary(
    summary: {
      'adherence',
      'author',
      'category',
      'dateAsserted',
      'effectiveDateTime',
      'effectivePeriod',
      'effectiveTiming',
      'encounter',
      'id',
      'identifier',
      'implicitRules',
      'medication',
      'meta',
      'modifierExtension',
      'status',
      'subject'
    },
    mandatory: {'medication', 'status', 'subject'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'MedicinalProductDefinition': ResourceElementSummary(
    summary: {
      'additionalMonitoringIndicator',
      'attachedDocument',
      'characteristic',
      'classification',
      'clinicalTrial',
      'code',
      'combinedPharmaceuticalDoseForm',
      'comprisedOf',
      'contact',
      'crossReference',
      'description',
      'domain',
      'id',
      'identifier',
      'implicitRules',
      'impurity',
      'indication',
      'ingredient',
      'legalStatusOfSupply',
      'marketingStatus',
      'masterFile',
      'meta',
      'modifierExtension',
      'name',
      'operation',
      'packagedMedicinalProduct',
      'pediatricUseIndicator',
      'route',
      'specialMeasures',
      'status',
      'statusDate',
      'type',
      'version'
    },
    mandatory: {'name'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'MessageDefinition': ResourceElementSummary(
    summary: {
      'base',
      'category',
      'contact',
      'date',
      'description',
      'eventCoding',
      'eventUri',
      'experimental',
      'focus',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'parent',
      'publisher',
      'purpose',
      'replaces',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'date', 'eventCoding', 'eventUri', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'MessageHeader': ResourceElementSummary(
    summary: {
      'definition',
      'destination',
      'eventCanonical',
      'eventCoding',
      'eventUri',
      'focus',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'reason',
      'response',
      'source'
    },
    mandatory: {'eventCanonical', 'eventCoding', 'eventUri', 'source'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'MolecularDefinition': ResourceElementSummary(
    summary: {
      'id',
      'identifier',
      'implicitRules',
      'location',
      'member',
      'meta',
      'modifierExtension',
      'moleculeType',
      'representation',
      'topology',
      'type'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'MolecularSequence': ResourceElementSummary(
    summary: {
      'concatenated',
      'extracted',
      'file',
      'id',
      'identifier',
      'implicitRules',
      'literal',
      'meta',
      'modifierExtension',
      'relative',
      'repeated',
      'type'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'NamingSystem': ResourceElementSummary(
    summary: {
      'contact',
      'date',
      'effectivePeriod',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'kind',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'uniqueId',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'date', 'kind', 'name', 'status', 'uniqueId'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'NutritionIntake': ResourceElementSummary(
    summary: {
      'basedOn',
      'code',
      'encounter',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'occurrenceDateTime',
      'occurrencePeriod',
      'partOf',
      'recorded',
      'status',
      'subject'
    },
    mandatory: {'status', 'subject'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'NutritionOrder': ResourceElementSummary(
    summary: {
      'dateTime',
      'groupIdentifier',
      'id',
      'implicitRules',
      'instantiatesCanonical',
      'intent',
      'meta',
      'modifierExtension',
      'requester',
      'status',
      'subject'
    },
    mandatory: {'dateTime', 'intent', 'status', 'subject'},
    modifier: {'implicitRules', 'intent', 'modifierExtension', 'status'},
  ),
  'NutritionProduct': ResourceElementSummary(
    summary: {
      'category',
      'code',
      'id',
      'implicitRules',
      'manufacturer',
      'meta',
      'modifierExtension',
      'nutrient',
      'status'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Observation': ResourceElementSummary(
    summary: {
      'basedOn',
      'code',
      'component',
      'derivedFrom',
      'effectiveDateTime',
      'effectiveInstant',
      'effectivePeriod',
      'effectiveTiming',
      'encounter',
      'focus',
      'hasMember',
      'id',
      'identifier',
      'implicitRules',
      'instantiatesCanonical',
      'instantiatesReference',
      'issued',
      'meta',
      'modifierExtension',
      'organizer',
      'partOf',
      'performer',
      'status',
      'subject',
      'valueAttachment',
      'valueBoolean',
      'valueCodeableConcept',
      'valueDateTime',
      'valueInteger',
      'valuePeriod',
      'valueQuantity',
      'valueRange',
      'valueRatio',
      'valueReference',
      'valueSampledData',
      'valueString',
      'valueTime'
    },
    mandatory: {'code', 'status'},
    modifier: {'focus', 'implicitRules', 'modifierExtension', 'status'},
  ),
  'ObservationDefinition': ResourceElementSummary(
    summary: {
      'category',
      'code',
      'contact',
      'date',
      'derivedFromCanonical',
      'derivedFromUri',
      'effectivePeriod',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'performerType',
      'publisher',
      'status',
      'subject',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'code', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'OperationDefinition': ResourceElementSummary(
    summary: {
      'affectsState',
      'base',
      'code',
      'contact',
      'date',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'instance',
      'jurisdiction',
      'kind',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'resource',
      'status',
      'synchronicity',
      'system',
      'title',
      'type',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'code', 'instance', 'kind', 'name', 'status', 'system', 'type'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'OperationOutcome': ResourceElementSummary(
    summary: {'id', 'implicitRules', 'issue', 'meta', 'modifierExtension'},
    mandatory: {'issue'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'Organization': ResourceElementSummary(
    summary: {
      'active',
      'description',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'name',
      'partOf',
      'type'
    },
    mandatory: {},
    modifier: {'active', 'implicitRules', 'modifierExtension'},
  ),
  'OrganizationAffiliation': ResourceElementSummary(
    summary: {
      'active',
      'code',
      'id',
      'identifier',
      'implicitRules',
      'location',
      'meta',
      'modifierExtension',
      'network',
      'organization',
      'participatingOrganization',
      'period',
      'specialty'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'PackagedProductDefinition': ResourceElementSummary(
    summary: {
      'attachedDocument',
      'characteristic',
      'containedItemQuantity',
      'copackagedIndicator',
      'description',
      'id',
      'identifier',
      'implicitRules',
      'legalStatusOfSupply',
      'manufacturer',
      'marketingStatus',
      'meta',
      'modifierExtension',
      'name',
      'packageFor',
      'packaging',
      'status',
      'statusDate',
      'type'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Parameters': ResourceElementSummary(
    summary: {'id', 'implicitRules', 'meta', 'parameter'},
    mandatory: {},
    modifier: {'implicitRules'},
  ),
  'Patient': ResourceElementSummary(
    summary: {
      'active',
      'address',
      'birthDate',
      'deceasedBoolean',
      'deceasedDateTime',
      'gender',
      'id',
      'identifier',
      'implicitRules',
      'link',
      'managingOrganization',
      'meta',
      'modifierExtension',
      'name',
      'telecom'
    },
    mandatory: {},
    modifier: {
      'active',
      'deceasedBoolean',
      'deceasedDateTime',
      'implicitRules',
      'link',
      'modifierExtension'
    },
  ),
  'PaymentNotice': ResourceElementSummary(
    summary: {
      'amount',
      'created',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'payment',
      'recipient',
      'status'
    },
    mandatory: {'amount', 'created', 'recipient', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'PaymentReconciliation': ResourceElementSummary(
    summary: {
      'amount',
      'created',
      'date',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'paymentIssuer',
      'period',
      'status',
      'type'
    },
    mandatory: {'amount', 'created', 'date', 'status', 'type'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Permission': ResourceElementSummary(
    summary: {
      'asserter',
      'combining',
      'date',
      'id',
      'identifier',
      'implicitRules',
      'justification',
      'meta',
      'modifierExtension',
      'rule',
      'status',
      'validity'
    },
    mandatory: {'combining', 'status'},
    modifier: {'combining', 'implicitRules', 'modifierExtension'},
  ),
  'Person': ResourceElementSummary(
    summary: {
      'active',
      'address',
      'birthDate',
      'deceasedBoolean',
      'deceasedDateTime',
      'gender',
      'id',
      'identifier',
      'implicitRules',
      'managingOrganization',
      'meta',
      'modifierExtension',
      'name',
      'telecom'
    },
    mandatory: {},
    modifier: {'active', 'implicitRules', 'modifierExtension'},
  ),
  'PersonalRelationship': ResourceElementSummary(
    summary: {
      'confidence',
      'group',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'relationshipType',
      'source',
      'target'
    },
    mandatory: {'relationshipType', 'source', 'target'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'PlanDefinition': ResourceElementSummary(
    summary: {
      'asNeededBoolean',
      'asNeededCodeableConcept',
      'contact',
      'date',
      'description',
      'effectivePeriod',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'type',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Practitioner': ResourceElementSummary(
    summary: {
      'active',
      'address',
      'birthDate',
      'deceasedBoolean',
      'deceasedDateTime',
      'gender',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'name',
      'telecom'
    },
    mandatory: {},
    modifier: {
      'active',
      'deceasedBoolean',
      'deceasedDateTime',
      'implicitRules',
      'modifierExtension'
    },
  ),
  'PractitionerRole': ResourceElementSummary(
    summary: {
      'active',
      'code',
      'display',
      'id',
      'identifier',
      'implicitRules',
      'location',
      'meta',
      'modifierExtension',
      'network',
      'organization',
      'period',
      'practitioner',
      'specialty'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'Procedure': ResourceElementSummary(
    summary: {
      'basedOn',
      'bodySite',
      'category',
      'code',
      'complication',
      'encounter',
      'focus',
      'id',
      'identifier',
      'implicitRules',
      'location',
      'meta',
      'modifierExtension',
      'occurrenceAge',
      'occurrenceDateTime',
      'occurrencePeriod',
      'occurrenceRange',
      'occurrenceString',
      'occurrenceTiming',
      'outcome',
      'partOf',
      'performer',
      'reason',
      'recorded',
      'recorder',
      'reportedBoolean',
      'reportedReference',
      'status',
      'statusReason',
      'subject'
    },
    mandatory: {'status', 'subject'},
    modifier: {'focus', 'implicitRules', 'modifierExtension', 'status'},
  ),
  'Provenance': ResourceElementSummary(
    summary: {
      'activity',
      'agent',
      'entity',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'occurredDateTime',
      'occurredPeriod',
      'patient',
      'recorded',
      'target'
    },
    mandatory: {'agent', 'target'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'Questionnaire': ResourceElementSummary(
    summary: {
      'code',
      'contact',
      'date',
      'derivedFrom',
      'description',
      'effectivePeriod',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'subjectType',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'QuestionnaireResponse': ResourceElementSummary(
    summary: {
      'author',
      'authored',
      'basedOn',
      'encounter',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'partOf',
      'questionnaire',
      'source',
      'status',
      'subject'
    },
    mandatory: {'questionnaire', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'RegulatedAuthorization': ResourceElementSummary(
    summary: {
      'attachedDocument',
      'basis',
      'case',
      'description',
      'holder',
      'id',
      'identifier',
      'implicitRules',
      'indication',
      'intendedUse',
      'meta',
      'modifierExtension',
      'region',
      'regulator',
      'status',
      'statusDate',
      'subject',
      'type',
      'validityPeriod'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'RelatedPerson': ResourceElementSummary(
    summary: {
      'active',
      'address',
      'birthDate',
      'gender',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'name',
      'patient',
      'relationship',
      'role',
      'telecom'
    },
    mandatory: {'patient'},
    modifier: {'active', 'implicitRules', 'modifierExtension'},
  ),
  'RequestOrchestration': ResourceElementSummary(
    summary: {
      'code',
      'groupIdentifier',
      'id',
      'identifier',
      'implicitRules',
      'instantiatesCanonical',
      'instantiatesUri',
      'intent',
      'meta',
      'modifierExtension',
      'priority',
      'status'
    },
    mandatory: {'intent', 'status'},
    modifier: {'implicitRules', 'intent', 'modifierExtension', 'status'},
  ),
  'Requirements': ResourceElementSummary(
    summary: {
      'contact',
      'date',
      'derivedFrom',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'imports',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ResearchStudy': ResourceElementSummary(
    summary: {
      'condition',
      'id',
      'identifier',
      'implicitRules',
      'keyword',
      'meta',
      'modifierExtension',
      'partOf',
      'period',
      'phase',
      'primaryPurposeType',
      'protocol',
      'recruitment',
      'region',
      'result',
      'site',
      'status',
      'studyDesign',
      'title',
      'whyStopped'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ResearchSubject': ResourceElementSummary(
    summary: {
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'period',
      'status',
      'study',
      'subject'
    },
    mandatory: {'status', 'study', 'subject'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'RiskAssessment': ResourceElementSummary(
    summary: {
      'code',
      'condition',
      'encounter',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'method',
      'modifierExtension',
      'occurrenceDateTime',
      'occurrencePeriod',
      'performer',
      'status',
      'subject'
    },
    mandatory: {'status', 'subject'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'Schedule': ResourceElementSummary(
    summary: {
      'active',
      'actor',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'name',
      'planningHorizon',
      'serviceCategory',
      'serviceType',
      'specialty'
    },
    mandatory: {'actor'},
    modifier: {'active', 'implicitRules', 'modifierExtension'},
  ),
  'SearchParameter': ResourceElementSummary(
    summary: {
      'aliasCode',
      'base',
      'code',
      'contact',
      'date',
      'description',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'type',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'base', 'code', 'description', 'name', 'status', 'type', 'url'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ServiceRequest': ResourceElementSummary(
    summary: {
      'asNeeded',
      'asNeededFor',
      'authoredOn',
      'basedOn',
      'bodySite',
      'bodyStructure',
      'category',
      'code',
      'doNotPerform',
      'encounter',
      'focus',
      'id',
      'identifier',
      'implicitRules',
      'instantiatesCanonical',
      'instantiatesUri',
      'intent',
      'location',
      'meta',
      'modifierExtension',
      'occurrenceDateTime',
      'occurrencePeriod',
      'occurrenceTiming',
      'orderDetail',
      'performer',
      'performerType',
      'priority',
      'quantityQuantity',
      'quantityRange',
      'quantityRatio',
      'reason',
      'replaces',
      'requester',
      'requisition',
      'specimen',
      'status',
      'subject'
    },
    mandatory: {'intent', 'status', 'subject'},
    modifier: {
      'doNotPerform',
      'implicitRules',
      'intent',
      'modifierExtension',
      'status'
    },
  ),
  'Slot': ResourceElementSummary(
    summary: {
      'appointmentType',
      'end',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'schedule',
      'serviceCategory',
      'serviceType',
      'specialty',
      'start',
      'status'
    },
    mandatory: {'end', 'schedule', 'start', 'status'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'Specimen': ResourceElementSummary(
    summary: {
      'accessionIdentifier',
      'combined',
      'condition',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'receivedTime',
      'status',
      'subject',
      'type'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'SpecimenDefinition': ResourceElementSummary(
    summary: {
      'collection',
      'contact',
      'date',
      'derivedFromCanonical',
      'derivedFromUri',
      'effectivePeriod',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'patientPreparation',
      'publisher',
      'status',
      'subjectCodeableConcept',
      'subjectReference',
      'timeAspect',
      'title',
      'typeCollected',
      'url',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'StructureDefinition': ResourceElementSummary(
    summary: {
      'abstract',
      'baseDefinition',
      'contact',
      'context',
      'contextInvariant',
      'date',
      'derivation',
      'experimental',
      'fhirVersion',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'keyword',
      'kind',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'type',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'abstract', 'kind', 'name', 'status', 'type', 'url'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'StructureMap': ResourceElementSummary(
    summary: {
      'const',
      'contact',
      'date',
      'experimental',
      'group',
      'id',
      'identifier',
      'implicitRules',
      'import',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'structure',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'group', 'name', 'status', 'url'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Subscription': ResourceElementSummary(
    summary: {
      'channelType',
      'contact',
      'content',
      'contentType',
      'end',
      'endpoint',
      'filterBy',
      'heartbeatPeriod',
      'id',
      'identifier',
      'implicitRules',
      'managingEntity',
      'maxCount',
      'meta',
      'modifierExtension',
      'name',
      'reason',
      'status',
      'timeout',
      'topic'
    },
    mandatory: {'channelType', 'status', 'topic'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'SubscriptionStatus': ResourceElementSummary(
    summary: {
      'error',
      'eventsSinceSubscriptionStart',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'status',
      'subscription',
      'topic',
      'type'
    },
    mandatory: {'subscription', 'type'},
    modifier: {'implicitRules', 'modifierExtension', 'type'},
  ),
  'SubscriptionTopic': ResourceElementSummary(
    summary: {
      'contact',
      'date',
      'derivedFrom',
      'effectivePeriod',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'trigger',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status', 'url'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Substance': ResourceElementSummary(
    summary: {
      'category',
      'code',
      'description',
      'expiry',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modifierExtension',
      'quantity',
      'status'
    },
    mandatory: {'code'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'SubstanceDefinition': ResourceElementSummary(
    summary: {
      'characterization',
      'classification',
      'code',
      'description',
      'domain',
      'grade',
      'id',
      'identifier',
      'implicitRules',
      'informationSource',
      'manufacturer',
      'meta',
      'modifierExtension',
      'moiety',
      'molecularWeight',
      'name',
      'note',
      'nucleicAcid',
      'polymer',
      'property',
      'protein',
      'referenceInformation',
      'relationship',
      'sourceMaterial',
      'status',
      'structure',
      'supplier',
      'version'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'SubstanceNucleicAcid': ResourceElementSummary(
    summary: {
      'areaOfHybridisation',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'numberOfSubunits',
      'oligoNucleotideType',
      'sequenceType',
      'subunit'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'SubstancePolymer': ResourceElementSummary(
    summary: {
      'class',
      'copolymerConnectivity',
      'geometry',
      'id',
      'identifier',
      'implicitRules',
      'meta',
      'modification',
      'modifierExtension',
      'monomerSet',
      'repeat'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'SubstanceProtein': ResourceElementSummary(
    summary: {
      'disulfideLinkage',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'numberOfSubunits',
      'sequenceType',
      'subunit'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'SubstanceReferenceInformation': ResourceElementSummary(
    summary: {
      'comment',
      'gene',
      'geneElement',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'target'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'SubstanceSourceMaterial': ResourceElementSummary(
    summary: {
      'countryOfOrigin',
      'developmentStage',
      'fractionDescription',
      'geographicalLocation',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'organism',
      'organismId',
      'organismName',
      'parentSubstanceId',
      'parentSubstanceName',
      'partDescription',
      'sourceMaterialClass',
      'sourceMaterialState',
      'sourceMaterialType'
    },
    mandatory: {},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'SupplyDelivery': ResourceElementSummary(
    summary: {
      'basedOn',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'occurrenceDateTime',
      'occurrencePeriod',
      'occurrenceTiming',
      'partOf',
      'stage',
      'status'
    },
    mandatory: {'stage', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'SupplyRequest': ResourceElementSummary(
    summary: {
      'authoredOn',
      'basedOn',
      'category',
      'id',
      'identifier',
      'implicitRules',
      'intent',
      'item',
      'meta',
      'modifierExtension',
      'occurrenceDateTime',
      'occurrencePeriod',
      'occurrenceTiming',
      'priority',
      'quantity',
      'requester',
      'status',
      'supplier'
    },
    mandatory: {'intent', 'item', 'quantity'},
    modifier: {'implicitRules', 'intent', 'modifierExtension', 'status'},
  ),
  'Task': ResourceElementSummary(
    summary: {
      'basedOn',
      'businessStatus',
      'code',
      'description',
      'doNotPerform',
      'encounter',
      'executionPeriod',
      'focus',
      'for',
      'groupIdentifier',
      'id',
      'implicitRules',
      'instantiatesCanonical',
      'instantiatesUri',
      'intent',
      'lastModified',
      'location',
      'meta',
      'modifierExtension',
      'owner',
      'partOf',
      'performer',
      'requestedPeriod',
      'requester',
      'status',
      'statusReason'
    },
    mandatory: {'intent', 'status'},
    modifier: {'doNotPerform', 'implicitRules', 'modifierExtension', 'status'},
  ),
  'TerminologyCapabilities': ResourceElementSummary(
    summary: {
      'contact',
      'copyright',
      'date',
      'experimental',
      'id',
      'identifier',
      'implementation',
      'implicitRules',
      'jurisdiction',
      'kind',
      'lockedDate',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'software',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'date', 'kind', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'TestPlan': ResourceElementSummary(
    summary: {
      'contact',
      'date',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'TestReport': ResourceElementSummary(
    summary: {
      'id',
      'identifier',
      'implicitRules',
      'issued',
      'meta',
      'modifierExtension',
      'name',
      'result',
      'score',
      'status',
      'testScript',
      'tester'
    },
    mandatory: {'result', 'status', 'testScript'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'TestScript': ResourceElementSummary(
    summary: {
      'contact',
      'date',
      'experimental',
      'id',
      'identifier',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'name', 'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'Transport': ResourceElementSummary(
    summary: {
      'basedOn',
      'code',
      'completionTime',
      'currentLocation',
      'description',
      'encounter',
      'focus',
      'for',
      'groupIdentifier',
      'id',
      'implicitRules',
      'instantiates',
      'lastModified',
      'location',
      'meta',
      'modifierExtension',
      'owner',
      'partOf',
      'requestedLocation',
      'requester',
      'status',
      'statusReason'
    },
    mandatory: {'currentLocation', 'requestedLocation'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'ValueSet': ResourceElementSummary(
    summary: {
      'contact',
      'date',
      'effectivePeriod',
      'experimental',
      'id',
      'identifier',
      'immutable',
      'implicitRules',
      'jurisdiction',
      'meta',
      'modifierExtension',
      'name',
      'publisher',
      'status',
      'title',
      'url',
      'useContext',
      'version',
      'versionAlgorithmCoding',
      'versionAlgorithmString'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
  'VerificationResult': ResourceElementSummary(
    summary: {
      'failureAction',
      'id',
      'implicitRules',
      'meta',
      'modifierExtension',
      'need',
      'status',
      'statusDate',
      'target',
      'targetLocation',
      'validationProcess',
      'validationType'
    },
    mandatory: {'status'},
    modifier: {'implicitRules', 'modifierExtension'},
  ),
  'VisionPrescription': ResourceElementSummary(
    summary: {
      'basedOn',
      'created',
      'dateWritten',
      'id',
      'implicitRules',
      'lensSpecification',
      'meta',
      'modifierExtension',
      'patient',
      'prescriber',
      'status'
    },
    mandatory: {
      'created',
      'dateWritten',
      'lensSpecification',
      'patient',
      'prescriber',
      'status'
    },
    modifier: {'implicitRules', 'modifierExtension', 'status'},
  ),
};
