name: fhir_r5_validation
description: Utility Library that Peforms Validation and Mapping Functionality.
version: 0.4.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_r5

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.19.0
  fhir_r5: ^0.4.0
  # fhir_r5_path: ^0.4.3
  fhir_r5_path:
    path: ../fhir_r5_path
  http: ^1.3.0

dev_dependencies:
  test: ^1.25.15
