name: fhir_r6_cds_hooks
description: CDS Hooks 2.0 client and service support for FHIR R6.
version: 0.7.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_r6
issue_tracker: https://github.com/fhir-fli/fhir_r6/issues

topics:
  - fhir
  - hl7
  - healthcare
  - cds-hooks
  - interoperability

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.0

dependencies:
  fhir_r6: ^0.7.0
  http: ^1.6.0

dev_dependencies:
  test: ^1.29.0
  very_good_analysis: ^10.0.0
