// Mocks generated by Mockito 5.4.6 from annotations
// in fhir_r6_auth/test/test_helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:convert' as _i5;
import 'dart:typed_data' as _i7;

import 'package:fhir_r6_auth/fhir_r6_auth.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuditEventStore_2 extends _i1.SmartFake
    implements _i3.AuditEventStore {
  _FakeAuditEventStore_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSessionConfig_3 extends _i1.SmartFake implements _i3.SessionConfig {
  _FakeSessionConfig_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSession_4 extends _i1.SmartFake implements _i3.Session {
  _FakeSession_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response>);

  @override
  _i4.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i7.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i4.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i4.Future<_i7.Uint8List>);

  @override
  _i4.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_1(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TokenStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorage extends _i1.Mock implements _i3.TokenStorage {
  MockTokenStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveTokens(_i3.SmartTokenResponse? tokens) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [tokens],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.SmartTokenResponse?> loadTokens() => (super.noSuchMethod(
        Invocation.method(
          #loadTokens,
          [],
        ),
        returnValue: _i4.Future<_i3.SmartTokenResponse?>.value(),
      ) as _i4.Future<_i3.SmartTokenResponse?>);

  @override
  _i4.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveAuthState(_i3.AuthState? state) => (super.noSuchMethod(
        Invocation.method(
          #saveAuthState,
          [state],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.AuthState?> loadAuthState() => (super.noSuchMethod(
        Invocation.method(
          #loadAuthState,
          [],
        ),
        returnValue: _i4.Future<_i3.AuthState?>.value(),
      ) as _i4.Future<_i3.AuthState?>);

  @override
  _i4.Future<bool> hasTokens() => (super.noSuchMethod(
        Invocation.method(
          #hasTokens,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [AuditLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuditLogger extends _i1.Mock implements _i3.AuditLogger {
  MockAuditLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuditEventStore get store => (super.noSuchMethod(
        Invocation.getter(#store),
        returnValue: _FakeAuditEventStore_2(
          this,
          Invocation.getter(#store),
        ),
      ) as _i3.AuditEventStore);

  @override
  _i4.Future<void> logEvent(_i3.AuditEvent? event) => (super.noSuchMethod(
        Invocation.method(
          #logEvent,
          [event],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logAuthenticationAttempt({
    required String? userId,
    String? ipAddress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logAuthenticationAttempt,
          [],
          {
            #userId: userId,
            #ipAddress: ipAddress,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logAuthenticationSuccess({
    required String? userId,
    String? ipAddress,
    Map<String, dynamic>? details,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logAuthenticationSuccess,
          [],
          {
            #userId: userId,
            #ipAddress: ipAddress,
            #details: details,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logAuthenticationFailure({
    String? userId,
    required String? reason,
    String? errorCode,
    String? ipAddress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logAuthenticationFailure,
          [],
          {
            #userId: userId,
            #reason: reason,
            #errorCode: errorCode,
            #ipAddress: ipAddress,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logSecurityViolation({
    required String? violation,
    required String? details,
    String? userId,
    String? ipAddress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logSecurityViolation,
          [],
          {
            #violation: violation,
            #details: details,
            #userId: userId,
            #ipAddress: ipAddress,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logTokenIssued({
    String? userId,
    required List<String>? scopes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logTokenIssued,
          [],
          {
            #userId: userId,
            #scopes: scopes,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logTokenRefreshed({String? userId}) => (super.noSuchMethod(
        Invocation.method(
          #logTokenRefreshed,
          [],
          {#userId: userId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logResourceAccess({
    required String? resourceType,
    required String? resourceId,
    required String? operation,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logResourceAccess,
          [],
          {
            #resourceType: resourceType,
            #resourceId: resourceId,
            #operation: operation,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i3.AuditEvent>> queryEvents({
    DateTime? startTime,
    DateTime? endTime,
    String? userId,
    _i3.AuditEventType? eventType,
    _i3.AuditSeverity? minSeverity,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryEvents,
          [],
          {
            #startTime: startTime,
            #endTime: endTime,
            #userId: userId,
            #eventType: eventType,
            #minSeverity: minSeverity,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i3.AuditEvent>>.value(<_i3.AuditEvent>[]),
      ) as _i4.Future<List<_i3.AuditEvent>>);
}

/// A class which mocks [SessionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionManager extends _i1.Mock implements _i3.SessionManager {
  MockSessionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SessionConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeSessionConfig_3(
          this,
          Invocation.getter(#config),
        ),
      ) as _i3.SessionConfig);

  @override
  _i4.Stream<Duration> get onTimeoutWarning => (super.noSuchMethod(
        Invocation.getter(#onTimeoutWarning),
        returnValue: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Stream<_i3.TimeoutReason> get onTimeout => (super.noSuchMethod(
        Invocation.getter(#onTimeout),
        returnValue: _i4.Stream<_i3.TimeoutReason>.empty(),
      ) as _i4.Stream<_i3.TimeoutReason>);

  @override
  bool get hasActiveSession => (super.noSuchMethod(
        Invocation.getter(#hasActiveSession),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<_i3.Session> startSession({
    required String? userId,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [],
          {
            #userId: userId,
            #metadata: metadata,
          },
        ),
        returnValue: _i4.Future<_i3.Session>.value(_FakeSession_4(
          this,
          Invocation.method(
            #startSession,
            [],
            {
              #userId: userId,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i4.Future<_i3.Session>);

  @override
  _i4.Future<void> recordActivity() => (super.noSuchMethod(
        Invocation.method(
          #recordActivity,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> endSession(_i3.TimeoutReason? reason) => (super.noSuchMethod(
        Invocation.method(
          #endSession,
          [reason],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> extendSession() => (super.noSuchMethod(
        Invocation.method(
          #extendSession,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> checkTimeoutsForTesting() => (super.noSuchMethod(
        Invocation.method(
          #checkTimeoutsForTesting,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
