// ignore_for_file: lines_longer_than_80_chars
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated from profiles-resources.json by
// fhir_generator/lib/src/generate_compartment_definitions.dart

/// The published compartments: for each compartment (keyed by
/// its focal resource type), the resource types that can be in
/// it and the search parameters through which they are.
///
/// compartmentdefinition.html: a resource is in the
/// compartment of the instance one of these parameters points
/// at. The focal resource is in its own compartment; that is
/// the search's business, not this table's. A type listed in the
/// published definition with no parameter is not here.
const Map<String, Map<String, List<String>>> compartmentDefinitions = {
  'Device': {
    'Account': ['subject'],
    'Appointment': ['actor'],
    'AppointmentResponse': ['actor'],
    'AuditEvent': ['agent'],
    'ChargeItem': ['enterer', 'performer-actor'],
    'Claim': ['detail-udi', 'item-udi', 'procedure-udi', 'subdetail-udi'],
    'Communication': ['recipient', 'sender'],
    'CommunicationRequest': ['information-provider', 'recipient'],
    'Composition': ['author'],
    'DetectedIssue': ['author'],
    'DeviceAlert': ['annunciator-device', 'source', 'subject'],
    'DeviceAssociation': ['device'],
    'DeviceRequest': ['performer', 'requester', 'subject'],
    'DiagnosticReport': ['subject'],
    'DocumentReference': ['author', 'subject'],
    'ExplanationOfBenefit': [
      'detail-udi',
      'item-udi',
      'procedure-udi',
      'subdetail-udi'
    ],
    'Flag': ['author'],
    'Group': ['member'],
    'Invoice': ['participant'],
    'List': ['source', 'subject'],
    'MessageHeader': ['receiver'],
    'Observation': ['device', 'subject'],
    'Provenance': ['agent'],
    'QuestionnaireResponse': ['author'],
    'RequestOrchestration': ['author'],
    'ResearchSubject': ['subject'],
    'RiskAssessment': ['performer'],
    'Schedule': ['actor'],
    'ServiceRequest': ['performer', 'requester'],
    'Specimen': ['subject'],
    'SupplyRequest': ['requester'],
  },
  'Encounter': {
    'CarePlan': ['encounter'],
    'ChargeItem': ['encounter'],
    'Claim': ['encounter'],
    'ClinicalAssessment': ['encounter'],
    'Communication': ['encounter'],
    'CommunicationRequest': ['encounter'],
    'Composition': ['encounter'],
    'Condition': ['encounter'],
    'DeviceRequest': ['encounter'],
    'DiagnosticReport': ['encounter'],
    'DocumentReference': ['context'],
    'EncounterHistory': ['encounter'],
    'ExplanationOfBenefit': ['encounter'],
    'MedicationAdministration': ['encounter'],
    'MedicationDispense': ['encounter'],
    'MedicationRequest': ['encounter'],
    'MedicationStatement': ['encounter'],
    'NutritionIntake': ['encounter'],
    'NutritionOrder': ['encounter'],
    'Observation': ['encounter'],
    'Procedure': ['encounter'],
    'QuestionnaireResponse': ['encounter'],
    'RequestOrchestration': ['encounter'],
    'ServiceRequest': ['encounter'],
    'VisionPrescription': ['encounter'],
  },
  'Group': {
    'AdverseEvent': ['subject'],
    'Appointment': ['actor', 'subject'],
    'AppointmentResponse': ['actor'],
    'AuditEvent': ['agent'],
    'CarePlan': ['subject'],
    'CareTeam': ['participant', 'subject'],
    'ChargeItem': ['subject'],
    'ClinicalAssessment': ['subject'],
    'Communication': ['subject'],
    'CommunicationRequest': ['subject'],
    'Condition': ['subject'],
    'Consent': ['actor', 'grantee', 'subject'],
    'DetectedIssue': ['subject'],
    'DeviceRequest': ['subject'],
    'DiagnosticReport': ['subject'],
    'DocumentReference': ['attester', 'author', 'subject'],
    'Encounter': ['participant', 'subject'],
    'EncounterHistory': ['subject'],
    'EpisodeOfCare': ['subject'],
    'Flag': ['subject'],
    'GenomicStudy': ['subject'],
    'Goal': ['subject'],
    'GuidanceResponse': ['subject'],
    'ImagingSelection': ['subject'],
    'ImagingStudy': ['subject'],
    'Invoice': ['subject'],
    'MeasureReport': ['subject'],
    'MedicationAdministration': ['subject'],
    'MedicationDispense': ['subject'],
    'MedicationRequest': ['subject'],
    'MedicationStatement': ['subject'],
    'NutritionIntake': ['subject'],
    'NutritionOrder': ['subject'],
    'Observation': ['specimen', 'subject'],
    'Procedure': ['subject'],
    'Provenance': ['agent'],
    'RequestOrchestration': ['participant', 'subject'],
    'ResearchStudy': ['eligibility'],
    'ResearchSubject': ['subject'],
    'RiskAssessment': ['subject'],
    'ServiceRequest': ['performer', 'subject'],
    'Specimen': ['subject'],
    'Task': ['subject'],
  },
  'Patient': {
    'Account': ['subject'],
    'AdverseEvent': ['subject'],
    'AllergyIntolerance': ['asserter', 'patient'],
    'Appointment': ['actor'],
    'AppointmentResponse': ['actor'],
    'AuditEvent': ['patient'],
    'Basic': ['author', 'patient'],
    'BiologicallyDerivedProductDispense': ['patient'],
    'BodyStructure': ['patient'],
    'CarePlan': ['patient'],
    'CareTeam': ['participant', 'patient'],
    'ChargeItem': ['subject'],
    'Claim': ['patient', 'payee'],
    'ClaimResponse': ['patient'],
    'ClinicalAssessment': ['subject'],
    'Communication': ['recipient', 'sender', 'subject'],
    'CommunicationRequest': [
      'information-provider',
      'recipient',
      'requester',
      'subject'
    ],
    'Composition': ['attester', 'author', 'subject'],
    'Condition': ['asserter', 'patient'],
    'Consent': ['subject'],
    'Contract': ['patient'],
    'Coverage': [
      'beneficiary',
      'paymentby-party',
      'policy-holder',
      'subscriber'
    ],
    'CoverageEligibilityRequest': ['patient'],
    'CoverageEligibilityResponse': ['patient'],
    'DetectedIssue': ['patient'],
    'DeviceAlert': ['subject'],
    'DeviceAssociation': ['operator', 'subject'],
    'DeviceRequest': ['performer', 'subject'],
    'DeviceUsage': ['patient'],
    'DiagnosticReport': ['subject'],
    'DocumentReference': ['author', 'subject'],
    'Encounter': ['patient'],
    'EncounterHistory': ['patient'],
    'EnrollmentRequest': ['subject'],
    'EpisodeOfCare': ['subject'],
    'ExplanationOfBenefit': ['patient', 'payee'],
    'FamilyMemberHistory': ['patient'],
    'Flag': ['patient'],
    'GenomicStudy': ['patient'],
    'Goal': ['patient'],
    'Group': ['member'],
    'GuidanceResponse': ['patient'],
    'ImagingSelection': ['patient'],
    'ImagingStudy': ['patient'],
    'Immunization': ['patient'],
    'ImmunizationEvaluation': ['patient'],
    'ImmunizationRecommendation': ['patient'],
    'Invoice': ['patient', 'recipient', 'subject'],
    'List': ['source', 'subject'],
    'MeasureReport': ['patient'],
    'MedicationAdministration': ['patient', 'subject'],
    'MedicationDispense': ['patient', 'receiver', 'subject'],
    'MedicationRequest': ['subject'],
    'MedicationStatement': ['subject'],
    'NutritionIntake': ['source', 'subject'],
    'NutritionOrder': ['patient'],
    'Observation': ['performer', 'subject'],
    'Patient': ['link'],
    'Person': ['patient'],
    'PersonalRelationship': ['source', 'target'],
    'Procedure': ['patient', 'performer'],
    'Provenance': ['patient'],
    'QuestionnaireResponse': ['author', 'subject'],
    'RelatedPerson': ['patient'],
    'RequestOrchestration': ['participant', 'subject'],
    'ResearchSubject': ['subject'],
    'RiskAssessment': ['subject'],
    'Schedule': ['actor'],
    'ServiceRequest': ['performer', 'subject'],
    'Specimen': ['subject'],
    'SupplyDelivery': ['patient'],
    'SupplyRequest': ['subject'],
    'Task': ['focus', 'patient'],
    'VisionPrescription': ['patient'],
  },
  'Practitioner': {
    'Account': ['subject'],
    'AdverseEvent': ['recorder'],
    'AllergyIntolerance': ['asserter'],
    'Appointment': ['actor'],
    'AppointmentResponse': ['actor'],
    'AuditEvent': ['agent'],
    'Basic': ['author'],
    'BiologicallyDerivedProductDispense': ['performer'],
    'CareTeam': ['participant'],
    'ChargeItem': ['enterer', 'performer-actor'],
    'Claim': ['care-team', 'enterer', 'payee', 'provider'],
    'ClaimResponse': ['requestor'],
    'ClinicalAssessment': ['performer'],
    'Communication': ['recipient', 'sender'],
    'CommunicationRequest': ['information-provider', 'recipient', 'requester'],
    'Composition': ['attester', 'author', 'subject'],
    'Condition': ['asserter'],
    'CoverageEligibilityRequest': ['enterer', 'provider'],
    'CoverageEligibilityResponse': ['requestor'],
    'DetectedIssue': ['author'],
    'DeviceAssociation': ['operator'],
    'DeviceRequest': ['performer', 'requester'],
    'DiagnosticReport': ['performer'],
    'DocumentReference': ['attester', 'author', 'subject'],
    'Encounter': ['participant', 'practitioner'],
    'EpisodeOfCare': ['care-manager'],
    'ExplanationOfBenefit': ['care-team', 'enterer', 'payee', 'provider'],
    'Flag': ['author'],
    'Group': ['member'],
    'Immunization': ['performer'],
    'Invoice': ['participant'],
    'Linkage': ['author'],
    'List': ['source'],
    'MedicationDispense': ['performer', 'receiver'],
    'MedicationRequest': ['requester'],
    'MedicationStatement': ['source'],
    'MessageHeader': ['receiver'],
    'NutritionIntake': ['source'],
    'NutritionOrder': ['requester'],
    'Observation': ['performer'],
    'Patient': ['general-practitioner'],
    'PaymentNotice': ['reporter'],
    'PaymentReconciliation': ['requestor'],
    'Person': ['practitioner'],
    'PractitionerRole': ['practitioner'],
    'Procedure': ['performer'],
    'Provenance': ['agent'],
    'QuestionnaireResponse': ['author', 'source'],
    'RequestOrchestration': ['author', 'participant'],
    'RiskAssessment': ['performer'],
    'Schedule': ['actor'],
    'ServiceRequest': ['performer', 'requester'],
    'Specimen': ['collector'],
    'SupplyDelivery': ['receiver', 'supplier'],
    'SupplyRequest': ['requester'],
    'VisionPrescription': ['prescriber'],
  },
  'RelatedPerson': {
    'AdverseEvent': ['recorder'],
    'AllergyIntolerance': ['asserter'],
    'Appointment': ['actor'],
    'AppointmentResponse': ['actor'],
    'Basic': ['author'],
    'CareTeam': ['participant'],
    'ChargeItem': ['enterer', 'performer-actor'],
    'Claim': ['payee'],
    'Communication': ['recipient', 'sender'],
    'CommunicationRequest': ['information-provider', 'recipient', 'requester'],
    'Composition': ['author'],
    'Condition': ['asserter'],
    'Coverage': ['paymentby-party', 'policy-holder', 'subscriber'],
    'DocumentReference': ['author'],
    'Encounter': ['participant'],
    'ExplanationOfBenefit': ['payee'],
    'Invoice': ['recipient'],
    'MedicationStatement': ['source'],
    'NutritionIntake': ['source'],
    'Observation': ['performer'],
    'Patient': ['link'],
    'Person': ['link'],
    'PersonalRelationship': ['source', 'target'],
    'Procedure': ['performer'],
    'Provenance': ['agent'],
    'QuestionnaireResponse': ['author', 'source'],
    'RequestOrchestration': ['participant'],
    'Schedule': ['actor'],
    'ServiceRequest': ['performer'],
    'SupplyRequest': ['requester'],
  },
};
