name: fhir_r6_bulk
description: Library to support the FHIR Bulk Data Access API (https://www.hl7.org/fhir/uv/bulkdata/index.html) for FHIR R6 resources.
version: 0.5.1
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_r6

topics:
  - fhir
  - hl7
  - healthcare
  - bulk-data
  - ndjson

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.0

dependencies:
  archive: ^4.0.7
  fhir_r6: ^0.5.0
  http: ^1.6.0
  mime: ^2.0.0
  universal_io: ^2.3.1

dev_dependencies:
  very_good_analysis: ^10.0.0
  test: ^1.29.0
