name: fhir_r6_bulk
description: Library to support the FHIR Bulk Data Access API (https://www.hl7.org/fhir/uv/bulkdata/index.html) for FHIR R4 resources.
version: 0.4.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_r6

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.0

dependencies:
  archive: ^4.0.4
  fhir_r6:
    path: ../fhir_r6
  http: ^1.3.0
  mime: ^2.0.0
  universal_io: ^2.2.2

dev_dependencies:
  test: ^1.25.15
