import 'data_types/address.dart';
import 'data_types/annotation.dart';
import 'data_types/attachment.dart';
import 'data_types/codeable_concept.dart';
import 'data_types/coding.dart';
import 'data_types/contact_detail.dart';
import 'data_types/contact_point.dart';
import 'data_types/dosage.dart';
import 'data_types/extension.dart';
import 'data_types/human_name.dart';
import 'data_types/identifier.dart';
import 'data_types/meta.dart';
import 'data_types/narrative.dart';
import 'data_types/period.dart';
import 'data_types/quantity.dart';
import 'data_types/range.dart';
import 'data_types/ratio.dart';
import 'data_types/reference.dart';
import 'data_types/timing.dart';
import 'data_types/usage_context.dart';

void main() {
  addressTest();
  annotationTest();
  attachmentTest();
  codeableConceptTest();
  codingTest();
  contactDetailTest();
  contactPointTest();
  dosageTest();
  extensionTest();
  humanNameTest();
  identifierTest();
  metaTest();
  narrativeTest();
  periodTest();
  quantityTest();
  rangeTest();
  ratioTest();
  referenceTest();
  timingTest();
  usageContextTest();
}
